### ISSUE TITLE
Scrolling more than one section at a time when scrolling fast on Apple trackpad?

### ISSUE THREAD

**Issue by BeauKelsey** [alvarotrigo/fullPage.js#1070]
When I scroll I go to the next section. When I scroll fast one time, I go to the next section... and then the next after that. Is there a way to ensure that you only scroll one section per scroll?

**Comment by alvarotrigo** [comment]
That's the way it works now. Make sure to use the latest version 2.6.0.
Can you reproduce that problem in the demo site? 
http://alvarotrigo.com/fullPage/

If so, which scroll device are you using? And which device?

**Comment by alvarotrigo** [comment]
Right. I noticed the bug introduced in the latest version.
Could you specify which scrolling device were you using? Was it an Apple laptop? Or a normal laptop with trackpad?

**Comment by louiswalch** [comment]
This is happening to me on an Apple laptop.

**Comment by alvarotrigo** [comment]
@louiswalch yeah, I localized the bug, I just need to test different trackpads to make sure I have it right. 
Meanwhile, you can go back to 2.5.9 if you want to avoid that problem.

**Comment by BeauKelsey** [comment]
I am using an Apple Magic Mouse and the track pad.

**Comment by louiswalch** [comment]
@alvarotrigo Thanks, that seems to make it work better on Mac trackpad. Oddly though I am noticing it will most of the time scroll twice JUST on the first scroll.

**Comment by hantq** [comment]
Yes, I met the same problem while using the Apple Trackpad.

**Comment by alvarotrigo** [comment]
Should be solved now in 2.6.1

**Comment by louiswalch** [comment]
Still happening for me more then with 2.5.9
Demo:
http://loui5.com/the-collection/debut

**Comment by alvarotrigo** [comment]
@louiswalch that's because of your scrolling speed. I might have another go at it... but it doesn't seem to have a simple solution... unless we want to go back to the compulsory timeout...

**Comment by louiswalch** [comment]
Thanks @alvarotrigo, slowing down the speed seems to have made the problem go away.

**Comment by SeFore** [comment]
Still happening for me. I'm using version: 3.0.2
any help, plz?

**Comment by alvarotrigo** [comment]
> Still happening for me. I'm using version: 3.0.2

Use a higher value for the option `scrollingSpeed`. For example: 


```javascript
new fullpage('#fullpage', {
    scrollingSpeed: 1000
});
```

**Comment by SeFore** [comment]
thanks, that was helpful. it fixed the problem.

**Comment by borisdiakur** [comment]
> Use a higher value for the option scrollingSpeed

Seriously? What is the scollingSpeed option good for if it breaks the whole thing starting at... I don’t know where.

Still happing in vue-fullpage.js@^0.1.5 which in turn uses fullpage.js@^3.0.8

Please reopen.

**Comment by alvarotrigo** [comment]
> Seriously? What is the scollingSpeed option good for if it breaks the whole thing starting at... I don’t know where.

If you read the docs you'll see it is not recommended to go lower than 700. 
Of course, you can decide to use a much higher value and you won't have any problem with it.

If you want to use a lower value, then I would recommend you to look into this pull request and the comments in it. They haven't been applied yet but they'll eventually do:
https://github.com/alvarotrigo/fullPage.js/pull/3826

**Comment by borisdiakur** [comment]
> If you read the docs you'll see it is not recommended to go lower than 700.

Where exactly?

> If you want to use a lower value, then I would recommend you to look into this pull request and the comments in it. They haven't been applied yet but they'll eventually do:

Nice. Subscribed. 👍
