### ISSUE TITLE
Demo issue

### ISSUE THREAD

**Issue by mrmartineau** [alvarotrigo/fullPage.js#12]
when using my scroll wheel (magic mouse) on the demo (http://alvarotrigo.com/fullPage/), the pages scroll jumps too far. For example, when I am on the first page, and scroll down to move to the second, I actually end up on the third. Make sense..? It seems to be too sensitive.

**Comment by RinkeRiezebos** [comment]
Hi Alvarotrigo!

Thanks for the great plugin. I am using it in my rails 4 apps in combination with turbolinks. 

On first page load (welcome page) scrolling works fine with normal speed, but when I go to another page and then go back to the welcome page scrolling has gone crazy. It seems like the sensitivity is really high then... (the anchors in the url change very fast and the slide jumps way too far) - this is in google chrome (see version below)

In Safari (8.0.2 (10600.2.5)) the sensitivity is always really high. 

I thought this was in line with the current thread, therefor adding my 2 cents here.

Using with:
Trackpad (slow and fast)
jquery.fullPage.js v. 2.5.6
Chrome 40.0.2214.94 (64-bit)
Mac OS X 10.10.1
Rails 4 with turbolinks

Unfortunately I do not have a website at the moment to show you..

**Comment by alvarotrigo** [comment]
@RinkeRiezebos open a new topic for your problem and provide a link to your site or a way to reproduce your problem (initialization and html markup)

**Comment by djvs** [comment]
I think you need to write code to detect the beginning and end of a scroll event to solve this problem.  Multiple users complaining to me about it, looking @ other plugins as result.  Just saying.

**Comment by alvarotrigo** [comment]
@djvs the plugin is working as expected if you use the default scrollingn speed. You can see how it works perfectly on Mac or Windows in [the demo site](http://alvarotrigo.com/fullPage/).

It sounds to me like you are changing the scrolling speed to a very fast one.
You can look for other plugins, but **none will solve you the problem in a proper way**. As much as they can do is forcing a delay of around 700 milliseconds to 1 second when you arrive to the section. That's how fullPage.js was working before and [many people complained](https://github.com/alvarotrigo/fullPage.js/issues?utf8=%E2%9C%93&q=scrolldelay) about that compulsory delay, so I improved fullPage.js to work more intelligently.

**Comment by mrmartineau** [comment]
I can confirm that it works well on the demo site. Thanks for making the improvements

**Comment by amandaobringer** [comment]
I am having the "fast scrolling" issue with Macs using the magic mouse or a trackpad when scrolling through slides. It seems fine going from section to section. I am using the code below to stop the vertical scrolling and move through a few slides with the mousewheel. Scrolling on these Mac devices skips through slides. A regular mouse seems fine. 

`onLeave: function(index, nextIndex, direction) {
                    loaded = false;
                    if (nextIndex == 3) {
                        $('#fullpage').on("mousewheel",function(e){
                            if(loaded){
                                loaded = false;
                                var delta = e.deltaY;
                                console.log(delta);

                                if(delta<0){ //down
                                    if(currentSlide===2){//if last slide
                                        $('#fullpage').off("mousewheel");
                                    }else{
                                        $.fn.fullpage.moveSlideRight();
                                        e.preventDefault();
                                        e.stopPropagation();
                                    }
                                }else{ //up
                                    if(currentSlide===0){//if first slide
                                        $('#fullpage').off("mousewheel");
                                    }else{
                                        $.fn.fullpage.moveSlideLeft();
                                        e.preventDefault();
                                        e.stopPropagation();
                                    }
                                }
                            }else{ //slide still loading, don't scroll
                                e.preventDefault();
                                e.stopPropagation();
                            }
                        });
                    }
                }
`

**Comment by alvarotrigo** [comment]
@amandaobringer you are doing funny things there with your `mousewheel`. Nothing I should know about.
It seems you have a javascript problem rather than a fullpage.js one. I'm afraid I don't provide support for your own javascript problems / scripts.

**Comment by amandaobringer** [comment]
Wow... thanks for the fast reply!! Certainly you are right that you can't support my js problems. 

It seems like when I am using the mousewheel to call moveSlideRight(); it calls that function twice. I think this is a problem with the inertia on these Mac devices. Was hoping there was something I could pass into the moveSlideRight() function to put a delay on fullpage moving to the next slide.

**Comment by alvarotrigo** [comment]
> Was hoping there was something I could pass into the moveSlideRight() function to put a delay on fullpage moving to the next slide.

Nop, the plugin doesn't provide anything for it I'm afraid.

**Comment by kikemx78** [comment]
Hi @alvarotrigo, I'm having the same Apple's Magic Mouse issue but only on Chrome [Version 44.0.2403.107 (64-bit)]. Firefox and IE are OK.

Even your demo page behaves wierd. 


Any idea of what could be wrong?


Congrats for your work!

**Comment by alvarotrigo** [comment]
@kikemx78 already being treated here: https://github.com/alvarotrigo/fullPage.js/issues/1389

**Comment by kikemx78** [comment]
@alvarotrigo it works for me!
thnx mate!

**Comment by CorpusCallosum** [comment]
FYI I was having the same issue, then noticed that I was calling   ```$('#fullpage').fullpage();``` twice accidentally. Removed the double call, and the problem is solved! Something to look out for.

**Comment by MrZiegler** [comment]
Hi @alvarotrigo I am having a trackpad issue, scrolling from 1st page to 2nd page works perfect, but when I simply touch my trackpad with 2 fingers on the 2nd page it scrolles back to the 1st page. Your demo site does not have this issue, so I am thinking that this is a configuration issue on my site. I sincerely hope to receive some assistance :)
The site: http://themarket.dk/

**Comment by interactiveRob** [comment]
Hi all,

For people still having the Chrome/Magic Mouse issue with the newest release. 
I noticed that setting scrollingSpeed to 900 or above when you call the `.fullpage();` function solved the issue. 

Example:
`jQuery('#fullpage').fullpage({
		scrollOverflow: true,
		scrollingSpeed: 850,
	});`

**Comment by alvarotrigo** [comment]
@interactiveRob, that's totally normal. Not recommended to go for anything lower than the default value.

**Comment by ProAnastasia** [comment]
@interactiveRob nope, this  value doesn't work :(

**Comment by Biswajit993** [comment]
I have some issues with Magic Mouse. When I scroll one time it's scroll two time

**Comment by alvarotrigo** [comment]
You've been replied already: 
https://github.com/alvarotrigo/fullPage.js/issues/314#issuecomment-1139445668
