### ISSUE TITLE
IE 11 + win 7 + HP EliteOne800 issue

### ISSUE THREAD

**Issue by vetzo** [alvarotrigo/fullPage.js#1245]
It seems that something is firing wheel events and the page is going up and down from by itself... on other browser the page is functioning ok...

**Comment by alvarotrigo** [comment]
Are you able to reproduce the problem in [the demo page](http://alvarotrigo.com/fullPage/)?

I'm not able to reproduce it in Browserstack.com

**Comment by vetzo** [comment]
i was reading later and i think that the problem is in touchscreen :/

because problem exists also on demo page... and this computer is owned by my client so i don't have access on it...

**Comment by alvarotrigo** [comment]
There shouldn't be a problem, [the issue](https://github.com/alvarotrigo/fullPage.js/issues/937) was solved time ago.

**Comment by vetzo** [comment]
i send them to demo page and the issue still exists, i even try to hack a plugin:

else{
                // moved up/down
						var seconds = new Date().getTime() / 1000;

						if ((seconds - lastClickTime) > 2) {
							scrollSection();
							lastClickTime = seconds;
						}
            }

 so that after one scroll is made for the next two seconds ignores all the scrolls, but after that time is passed the site once again goes up and down... maybe i can alter one of your demos to catch all events and then send it to you...

**Comment by alvarotrigo** [comment]
Now you are talking about another problem... scrolling once scroll multiple sections?

Before you said "the page is going up and down from **by itself**.". That means. no action from the mouse wheel.

**Comment by vetzo** [comment]
here is explanation for the bug from the client:

on the first few scrolls everything is working fine, after that on one wheel scroll it goes two pages down, and after that it goes random up and down... the bug is only visible on ie11, while on the chrome and firefox everything is going smooth...

also they have 4 of this hp computers and on every one its the same problem...

**Comment by vetzo** [comment]
and btw. on autoScrolling:false demo everything is fine, there is no random movement or scrolling or nothing... and i also send them link to similar plugin: http://www.thepetedesign.com/demos/onepage_scroll_demo.html to see if they have the same problems with this plugin...

**Comment by drawcard** [comment]
I was also getting some intermittent problems with section panels skipping when you use a Magic Mouse or a Macbook Air Touchpad (running the latest version of Chrome). When you scroll one panel down, sometimes it would skip and move two panels down (or up). It only occurred after I updated to the latest version of Fullpage JS via Bower. It also comes and goes too, like it's a random trigger that's causing it. I hesitated reporting it as I wasn't sure if it was an isolated case but reading this bug report has made me speak up about it.

I can provide more system info in seperate thread if needed.

Cheers
C

**Comment by alvarotrigo** [comment]
@vetzo I'm afraid I can not provide any solution for it. 
I was not able to reproduce it in Browserstack and I do not have access to any touch screen computer with IE 11 where I can test it.

Is your client testing it in [the demo page](http://alvarotrigo.com/fullPage/)?
Are they using touch or mouse to scroll the site? 

In any case, there's nothing I can do unless somebody can test it by their own. That's what some people did in [this topic](https://github.com/alvarotrigo/fullPage.js/issues/937) and seemed to have solved the problem for them.

**Comment by jsgeeker** [comment]
I also encountered this problem（in 2.5.3）.

IE11 + WIN8 (only):
When I stay in a the middle of the page,
I didn't scroll my mouse and moved the mouse quickly to to the bottom right corner/left corner. The page is going up and down from by itself.


But this problem has been solved in the newest version.(2.6.5)

**Comment by alvarotrigo** [comment]
> （in 2.5.3）.

I'm afraid I only provide support for the latest version of fullPage.js (2.6.5) in this case.

**Comment by alvarotrigo** [comment]
Can you confirm if the error persists in the latest version of fullPage.js? 2.6.7 ?

**Comment by alvarotrigo** [comment]
Closed until a replied is provided.

**Comment by FilipeDornelas** [comment]
> on the first few scrolls everything is working fine, after that on one wheel scroll it goes two pages down, and after that it goes random up and down... the bug is only visible on ie11, while on the chrome and firefox everything is going smooth...

I had the same problem. Solved by changing the anchors name that looks like my section id (case sensitive).

**Comment by alvarotrigo** [comment]
@FilipeDornelas  that's detailed in the documentation multiple times:

> Be careful! data-anchor tags can not have the same value as any ID element on the site (or NAME element for IE).
