### ISSUE TITLE
Auto-height not working with `scrollBar:true` and `fitToSection:true`

### ISSUE THREAD

**Issue by jojomcbobo** [alvarotrigo/fullPage.js#1489]
Hello, thanks so much for this plugin it's amazing! I've been trying for a couple of days to get a footer section working but I'm getting some odd behavior I can't fix: http://www.jonasnaimark.com/temp/fullscreentest/Test.html#page12

The page will sometimes auto scroll up one section, other times it will stay but the nav will go back up after a delay. Often when hitting up from the footer it will jump up 2 sections instead of one. Any tips on how to fix this?

Thanks!

**Comment by alvarotrigo** [comment]
It seems to be related with the use of `scrollBar:true`.
Thanks for reporting it. I'll investigate it.

**Comment by alvarotrigo** [comment]
As a workaround, you can use `fitToSection:false` to prevent the problem.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.7.0

**Comment by jojomcbobo** [comment]
Wow thanks for the update! It still seems to be happening on 2.7.0 though if scrollBar:true. Changing fitToSection doesn't fix it either. It works fine if scrollBar:false.

Updated to 2.7.0 with the same bug:
http://www.jonasnaimark.com/temp/fullscreentest/Test.html#page12

**Comment by alvarotrigo** [comment]
Right. I'll take a look with more calm for the next release. 
However it doesn't seem to be a very simple problem to solve.

**Comment by alvarotrigo** [comment]
> Changing fitToSection doesn't fix it either. 

Not sure to understand you there. 
Using `fitToSection:false` should fix the problem.

**Comment by jojomcbobo** [comment]
Thanks again for looking at it!

**Comment by rootkowski** [comment]
Not sure this will help in your case, but I needed to disable fitToSection on a project but it would still kick in on resize, rotate and sometimes on nav click (the section would be refitted over and over despite autoScrolling and fitToSection set to false). My workaround for that was to set fitToSectionDelay to 3600000 which I believe is one hour in milliseconds. That way the current section doesn't scroll to fill the screen, it stays where you want it, which is very good when you have a lot of content in sections and want to be able to view it all on a phone.

**Comment by alvarotrigo** [comment]
@rootkowski update to the latest version 2.7.4.

**Comment by rootkowski** [comment]
Thanks a lot for the super fast reply! :) 
This has definitely fixed it. Tested after removing the delay option.

**Comment by jojomcbobo** [comment]
Hi rootkowski, how did you fix it? I don't see the answer posted here. Thanks!

**Comment by alvarotrigo** [comment]
@jojomcbobo 

> As a workaround, you can use fitToSection:false to prevent the problem.

**Comment by jojomcbobo** [comment]
I still seem to have the issue: http://www.jonasnaimark.com/temp/fullscreentest/Test.html#page12

If you scroll to the last page the menu dot will bounce back up sometimes, then if you hit up it will skip a section.

**Comment by rootkowski** [comment]
@jojomcbobo Make sure you're using the latest version of fullPage.js (at least 2.7.4).

**Comment by jojomcbobo** [comment]
I'm on the latest version and it seems like with scrollbar=true it still doesn't work. Example: http://www.jonasnaimark.com/temp/fullscreentest/Test.html#page12  hit down and it will bounce back up.

**Comment by alvarotrigo** [comment]
@jojomcbobo that's because you have to use `fitToSection:false`.
Now it works ok with `fitToSection:false` in the latest 2.7.4.

**Comment by alvarotrigo** [comment]
Fixed on the [development branch 2.7.8](https://github.com/alvarotrigo/fullPage.js/blob/dev/jquery.fullPage.js)

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.8.
