### ISSUE TITLE
'fitToSection: false' not being accepted

### ISSUE THREAD

**Issue by jessicaalouette** [alvarotrigo/fullPage.js#1499]
### To duplicate: 

* 'fitToSection: false' added to the fullpage initialization

### Expected result: 

* fitToSection disabled
* User has ability to stop in the middle of a section

### Actual result: 

* fitToSection remains enabled
* User cannot stop for more than a second in the middle of a section, without it going back to the top.

**My full initialization code:**

```javascript
$('#fullpage').fullpage({
        paddingTop: '60px',
        fixedElements: 'nav',
        anchors: ['home', 'howitworks', 'whattodo', 'contact'],
        navigationTooltips: ['Home','How it Works', 'What to Do', 'Get in Touch'],
        touchSensitivity: 15,
        navigation: true,
        autoScrolling: false,
        fitToSection: false,
});
```

Tested on Chrome 45, Firefox 40, IE9 (all on Windows 8.1).

**Comment by alvarotrigo** [comment]
Right. Introduced in 2.7.0.
Thanks for reporting it!

**Comment by adamwalter** [comment]
Looking forward to this fix. In the meantime, I've set `fitToSectionDelay` very high so that the user never sees it during normal use.

**Comment by alvarotrigo** [comment]
@adammcarth next version will solve it.

**Comment by adammcarth** [comment]
Did I report this somewhere else or something? It was so long ago, I haven't used fullPage.js in ages hahaha.

**Comment by alvarotrigo** [comment]
@adammcarth I'm not sure what are you talking about :)

**Comment by adammcarth** [comment]
LOL, I think you might have just randomly mentioned me in this issue (I probably reported something ages ago so my name came up in mention suggestions. I think you might have meant @adamwalter ;)

**Comment by adammcarth** [comment]
Thanks for thinking of me though @alvarotrigo. Good work people. That's some fine issue solving.

**Comment by alvarotrigo** [comment]
Hahaha :) Right. My mistake :D

**Comment by joaomisturini** [comment]
I still have the same issue in version 2.7.1. Apparently, the option turns true again when the active section changes. Any help?

**Comment by alvarotrigo** [comment]
@joaomisturini as I said

> next version will solve it.

Which means, 2.7.2.

**Comment by joaomisturini** [comment]
Oh, didn't really saw the dates in this issue. I'm really sorry.

**Comment by alvarotrigo** [comment]
Solved in 2.7.2

**Comment by flyingbaba** [comment]
It is not solved, problem appear in fullPage 2.9.4 in mobile devices

**Comment by alvarotrigo** [comment]
> It is not solved, problem appear in fullPage 2.9.4 in mobile devices

Please provide an isolated reproduction.

**Comment by christophethibault** [comment]
It is not solved, problem appear in fullPage 2.9.5 and 2.9.6 in mobile devices (Tested with Android 8)

### To duplicate
- 'fitToSection: false' added to the fullpage initialization

### Actual result: Firefox Focus - (Android) and Chrome (Android)
- fitToSection remains enabled

### My full initialization code
```
$('#fullpage').fullpage({
    autoScrolling: false,
    fitToSection: false,
    verticalCentered: false,
    scrollBar:true,
    recordHistory: true,
    anchors: ['Accueil','xxxx','yyyy','zzzz']    
});
```

**Comment by alvarotrigo** [comment]
@christophethibault I can't reproduce the issue in Android by using your initialisation. Tested using Browserstack on Galaxy S8+ with Android and Chrome. 
Also, working perfectly in iPhone in Chrome & Safari.

**Comment by christophethibault** [comment]
@alvarotrigo thank you for your reply.

I may not have understood the operating principle of the "fitToSection"
function .

My problem is this: I have a section that is higher than the height of the
screen and I wish I could display it correctly. She is currently truncated
...

I saw your answers (# 2800 responsiveWidth and responsiveHeight) but
without success.
In any case, thank you for your work (fullpage)


2018-04-07 13:29 GMT+02:00 Álvaro <notifications@github.com>:

**Comment by alvarotrigo** [comment]
> My problem is this: I have a section that is higher than the height of the
> screen and I wish I could display it correctly. She is currently truncated

You'll have to use scrollOverflow:true as [in this example](https://alvarotrigo.com/fullPage/examples/scrolling.html) or use the class `fp-auto-height` and use  autoScrolling:false to turn off the auto scrollling behaviour.

**Comment by christophethibault** [comment]
Hahaha... So simple !! You are my hero !!
Thanks for everything !
