### ISSUE TITLE
Page section height not always 100% of window height on load

### ISSUE THREAD

**Issue by brianedelman** [alvarotrigo/fullPage.js#1830]
I am having an issue in developing a site where sometimes the page will load just 10px (or so) too short of 100% of the window. It doesn't always happen, though.  It is exactly the height of the event loading description of the Chrome browser (at the bottom of the window).

I had tried triggering a forced resize to solve the problem and it seemed to be working, but now it isn't.   Here is a [server reproduction](http://dev.antarcti.cc/crownhats/).  

I have all the foundation css remaining in the file just because that could be part of the issue.  I have deleted as much of my personal css (at bottom of the file) as possible.  The problem WAS happening on a fullsize window initially, but as I deleted some css or elements it disappeared.  It is no only happening on a small window size.  I couldn't reproduce the large window effect as I was deleting things.

when I do resize the page, it automatically fixes it.

Let me know if I need to delete more for you.

**Comment by alvarotrigo** [comment]
As the problem can not be reproduced in any of [the demo pages](http://alvarotrigo.com/fullPage/) please add an isolated reproduction of the issue in jsfiddle or codepen or even in your own host, but remove any unnecessary css and external JS.

**Comment by brianedelman** [comment]
Corrected original question above with reproduction.  Thanks!

**Comment by alvarotrigo** [comment]
Please remove any console errors such as "Uncaught TypeError: $(...).foundation is not a function"

Also, which browser or OS are you using?

**Comment by brianedelman** [comment]
Error removed.  Using chrome primarily, but the problem also appears in safari and firefox.

**Comment by alvarotrigo** [comment]
I don't see any problem in Chrome on Windows on your [reproduction online](http://dev.antarcti.cc/crownhats/). I'll test it on Mac when I arrive home.

**Comment by brianedelman** [comment]
Okay, yes I am on mac.  To be extra clear the problem is only happening now
when the window is smaller. Like below 640px.  But it was happening on
large screens.  Thanks!

On Mon, Feb 15, 2016 at 12:08 PM, Álvaro <notifications@github.com> wrote:

> I don't see any problem in Chrome on Windows on your reproduction online
> <http://dev.antarcti.cc/crownhats/>. I'll test it on Mac when I arrive
> home.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1830#issuecomment-184304512>
> .
>



-- 
Best Wishes,

Brian Edelman
brianedelman.net

**Comment by alvarotrigo** [comment]
Yep, I see it now. It seems to be related with foundation CSS media queries. I'll take a look later.

**Comment by playnox** [comment]
Make sure HTML and BODY height is set to 100%, as well as each section height - I had this problem before...
Basically each parent element starting from HTML to your section has to be set with same height.
Thanks

**Comment by alvarotrigo** [comment]
Same problem as #1502.
Solved in the dev branch in the non minified fullpage.js. (2.7.8)

**Comment by brianedelman** [comment]
Thank you!

On Wed, Feb 17, 2016 at 10:05 AM, Álvaro <notifications@github.com> wrote:

> Same problem as #1502
> <https://github.com/alvarotrigo/fullPage.js/issues/1502>.
> Solved in the dev branch in the non minified fullpage.js. (2.7.8)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/alvarotrigo/fullPage.js/issues/1830#issuecomment-185243176>
> .
>



-- 
Best Wishes,

Brian Edelman
brianedelman.net

**Comment by alvarotrigo** [comment]
Solved in fullpage.js 2.7.8.

**Comment by 3em** [comment]
still the same problem
no padding on section
still some times section more height than window height

**Comment by alvarotrigo** [comment]
@3em you'll have to provide an isolated reproduction in jsfiddle or codepen.
