### ISSUE TITLE
Don't want to scroll to the bottom of a section

### ISSUE THREAD

**Issue by NiklasLazinbee** [alvarotrigo/fullPage.js#1854]
Hallo,
for mobile divices with small screens I set `$.fn.fullpage.setAutoScrolling(false)`.
I have sections in which the height is more than screenheight, when I use the menu to skip to a section, fullPage.js animates to the bottom of these section. But I want to go to the top of  the section. I don't want to use `$.fn.fullpage.setFitToSection(true)` because than I at first go to the bottom and than the script jumps to the top of the section.

Is there a way that fullPage.js animates to the top of a section and not to the bottom?

Best regards
Niklas

**Comment by alvarotrigo** [comment]
> Is there a way that fullPage.js animates to the top of a section and not to the bottom?

fullPage.js will animate to the top if you come from a section above the destination one.
It will animate to the bottom if you come from a section below the destination one.

Make sure you use the latest fullpage.js (2.7.8) to get this result.

**Comment by NiklasLazinbee** [comment]
I find a solution which works for me, but I don't fi it works for everyone because I don't know all dependencies:
I change line 1294 from
`if(element.outerHeight() > windowsHeight){`
to 
`if(element.outerHeight() > windowsHeight && options.autoScrolling){`
and line 1302 from
`else if(isScrollingDown){`
to 
`else if(isScrollingDown && options.autoScrolling){`

Beste regards 
Nikls

**Comment by pebarrault** [comment]
Hi,

I'm in the same case despite using the 2.7.8 version. 

This fix works for me, thanks !

**Comment by dceonline** [comment]
Hi,

that works for me too. Maybe you can add an option like 'scrollToSectionTop' true|false, to always scroll to the top off a section. That would be a nice feature if autoscrolling is disabled and someone uses the navbar.

Regards
Ortwin

**Comment by codercooooder** [comment]
I'm not sure if I implemented this correctly, but as I see it this fix requires you turn off autoScrolling?  It is an alright fix because it preserves the menu functionality, but for me I lose all scrolling animation (which I'd like to retain).  I woudl love it if someone could come up with a fix that would allow me to keep autoscrolling on and instead scroll to the top from section when scrolling up?

**Comment by Klasyczny** [comment]
Hello, 
while solution provided in 2.7.8 and proposed here by Niklas works fine on a computer or google emulated devices, it doesnt work on mobile devices. There, skipping to section still jumps to bottom instead of top of it. I hope this isn't the impassable problem and can be handled.

Regards,
Klasyczny

**Comment by alvarotrigo** [comment]
> There, skipping to section still jumps to bottom instead of top of it. I hope this isn't the impassable problem and can be handled.

I'm afraid I'm not able to reproduce your issue. It works as expected for me.
Provide an isolated reproduction if you think its not working as I said previously:

> fullPage.js will animate to the top if you come from a section above the destination one.
It will animate to the bottom if you come from a section below the destination one.

**Comment by starlord** [comment]
> fullPage.js will animate to the top if you come from a section above the destination one.
It will animate to the bottom if you come from a section below the destination one

From a user point of view i would expect animate to top if coming from a section below the destination one. the thing is that the same link navigates me to two different positions. so if i want to go again to beginning of the previous section (like it worked before from above) I get a different behaviour now.

An option for this would be really cool therefore. imho the same link should always lead to same position. in this case top of section.

**Comment by starlord** [comment]
@NiklasLazinbee Your solution works great so far. Thx!

**Comment by pfried** [comment]
I am using fullpage on a responsive site am doing and it would be very helpful to be able to scroll to the top. If the viewport is very small it is hard for users to know where they are if there is no headline. On desktop this is totally fine since there are enough fixpoints. But on a mobile device it is crucial to scroll to the top of the section as there will be a headline or any other entry point

**Comment by codercooooder** [comment]
Indeed, it would really be wonderful if fullpage could autoscroll not only to the top of sections from below with gesture, but also with keyboard control.  

Actually, I discovered that this is why I thought the solution devised by @NiklasLazinbee's solution didn't seem to work for me. I didn't realize there was a difference between keyboard-controlled scrolling and gesture controlled autoscrolling. His fix does work for gesture scrolling, but it doesn't seem to change the section target reference to top for keyboard scrolling from bellow.

**Comment by bdkaat** [comment]
I also need a solution for this. I never want a section to scroll to the bottom.

**Comment by sohrabzia** [comment]
I got your point, I have section bigger then the view port height, when i navigate to that section it goes to top of that section but after a moment it automatically scrolls to bottom of same section. which is not enough time to see what is at the top of section as it scrolls up automatically.

**Comment by alvarotrigo** [comment]
@sohrabzia  That's probably because you are using `fitToSection:true`. Just turn it off.

**Comment by sohrabzia** [comment]
Thank you so much @alvarotrigo  , that is a relief. Thanks again :)

**Comment by Saradimi** [comment]
Hi, same problem for me.
I usually set section's height to auto to allow higher sections and i don't want the menu to scroll to the bottom of them even if if you come from a section below the destination one.
An option to set this would be really appreciable.
Waiting for this, i have to use an old version of your plugin (2.6) which don't implement this feature.
Thanks in advance.

**Comment by CodeDredd** [comment]
@Saradimi I made a gist with that option.
[fullPage.js with new Option](https://gist.github.com/CodeDredd/4c2040cefbe1e00b7b04b778003c7ccf)

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2.
A new option was added `bigSectionsDestination`. Check the docs for more info about its usage.

**Comment by SweetyBrittany** [comment]
I meet the same problem with sohrabzia. I have spend about 5 hours on it. If the problem is not solved, i will work night shift. Fortunately the answer of setting `fitToSection: false` works for me. I am really grateful now. @alvarotrigo  @sohrabzia

**Comment by JerryGreen** [comment]
I want this feature not for only big sections 😞

**Comment by JerryGreen** [comment]
I want this feature not for only big sections 😞 

For my case, the section is smaller than viewport and I want that my scroll is always sticks to the bottom of section, whether I scroll down or up.

A bit more clarification:

Not that necessary to stick to exactly bottom, top is ok too - It's not that important. The important thing here - it should work simplier, less smart and *not checking the direction of scroll*.

**Comment by hckrmoon** [comment]
I think adding new option like `sectionDestination` set to 'auto' as default 

and if the value 'top' 

```javascript
else if(isScrollingDown || (isResizing && element.is(':last-child')) ){
  //The bottom of the destination will be at the bottom of the viewport
  position = sectionBottom;
}
```

to 

```javascript
else if(sectionDestination !== 'top' || isScrollingDown || (isResizing && element.is(':last-child')) ){
  //The bottom of the destination will be at the bottom of the viewport
  position = sectionBottom;
}
```

could fix this issue. 

@alvarotrigo Could you give me your opinion ? 
If you think this is a proper enhancement,  I can make PR.

**Comment by vdomah** [comment]
@hckrmoon thanks! that's exactly what I've searched. Allowed to scroll only to top of sections even for smaller.

**Comment by tylerjordan1994** [comment]
@hckrmoon perfect!! Thanks so much! Why isn't this a feature?

**Comment by TylerBarnes** [comment]
@alvarotrigo was any more thought given to this? @hckrmoon's fix looks good but I can't use it since I'm using `react-fullpage` installed from npm.

**Comment by alvarotrigo** [comment]
@TylerBarnes nothing new.

**Comment by hallowichig0** [comment]
@vdomah thank you for this solution. This really help when you are using auto-height footer.
