### ISSUE TITLE
Links don't work inside a section when scrollOverflow:true

### ISSUE THREAD

**Issue by apatheiagit** [alvarotrigo/fullPage.js#2117]
### Description
Internal and external links don't work, nothing happens when one clicks it.

### Link to isolated reproduction with no external CSS / JS
http://jsfiddle.net/97tbk/1335/

### Steps to reproduce it
1. Set scrollOverflow:true
2. Put enough text in a section for scroll bar appears
3. Add a usual link inside the text (<a href="http://blablabla.com">...</a>)
4. Click the link, nothing happens

### Versions 
OS: win7 (version 6.1.7601)
Browser: 
1. Opera 38.0.2220.31
2. Google Chrome 51.0.2704.103 m (64-bit)
3. Firefox 45.0.2

Additionl remarks:
1. It works in IE 11.0.9600.18230
2. Everything is fine when there is no scroll bar into a section.

**Comment by alvarotrigo** [comment]
Thanks for reporting it.
This is due to a bug in iScroll.js: https://github.com/cubiq/iscroll/issues/783

The solution so far seems to be something similar to what @martarakoczy suggested in [her answer](https://github.com/alvarotrigo/fullPage.js/issues/2035#issuecomment-224549092).

**Comment by Lynge-nielsen** [comment]
I have the same problem.
Is there any solution to it ?

**Comment by alvarotrigo** [comment]
> Is there any solution to it ?

Read above:

> solution so far seems to be something similar to what @martarakoczy suggested in her answer.

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.2

**Comment by jackyon** [comment]
@alvarotrigo, looks like this issue still happened on normal form elements, 

for example:
<input type="submit" name="sendbutton" id="sendbutton" class="sendbutton" value="Submit">

in this case, the button still can not clickable.

plz advise, thx!

**Comment by alvarotrigo** [comment]
@jackyon provide a reproduction in jsfiddle or codepen.

**Comment by AlexVanderbist** [comment]
I'm having the same issue. Specifically on mobile

**Comment by alvarotrigo** [comment]
@AlexVanderbist  Download the latest fullpage.js 2.8.4
