### ISSUE TITLE
Disable Autoplay for YouTube Embed

### ISSUE THREAD

**Issue by leemediagroup** [alvarotrigo/fullPage.js#2214]
### Description
I am embedding a youtube video on the second section of my website, and it is autoplaying anytime we enter the section. I have added autoplay=0 to the youtube embed code, but it seems to be autoplaying no matter what so I'm not sure if there is another setting I need to change. 

### Versions 
Mac OSX Chrome, version 2.8.4 of fullPage.js

**Comment by alvarotrigo** [comment]
Check [the docs](https://github.com/alvarotrigo/fullPage.js#auto-playpause-embedded-media)

**Comment by leemediagroup** [comment]
That's where I've been looking, but the video is playing as thought i have data-autoplay set for the section, but I don't. Is there an attribute that does the opposite (prevents it from autoplaying)?

**Comment by alvarotrigo** [comment]
Please provide an isolated reproduction in jsfiddle or codepen.

**Comment by leemediagroup** [comment]
https://codepen.io/tabytharourke/pen/bZJdZZ

I left out all of the CSS and everything, but you'll see if you scroll to the second screen, the video starts playing. I'm trying to figure out how to prevent that.

**Comment by alvarotrigo** [comment]
Seems to be a bug.

**Comment by dmrc1143** [comment]
Hi, I am also faced with this problem and I see the problem has fixed here: https://github.com/alvarotrigo/fullPage.js/releases/tag/2.8.3
I updated my dependencies but yet problem is going on.. 
@leemediagroup is your problem solved with this update?

**Comment by alvarotrigo** [comment]
@dmrc1143 definitely not fixed there. It is clearly a bug that needs to be solved.
