### ISSUE TITLE
Require.js: Uncaught ReferenceError: IScroll is not defined

### ISSUE THREAD

**Issue by khleealton** [alvarotrigo/fullPage.js#2250]
Thanks for your awesome library – Fullpage!
My team is currently upgrading the version from 2.7.6 to 2.8.6 in requireJS

However, we met the following JS error:
“Uncaught ReferenceError: IScroll is not defined”

I have tried to include your customized IScroll into the same JS file we are using fullpage.js.
May I know if you have any clue on this?

**Comment by alvarotrigo** [comment]
It is due to the use of requiere.js that won't expose the the IScroll variable globally.

**Comment by alvarotrigo** [comment]
The problem when using `require` is that makes dependencies compulsory as far as I know. 
And scrollOverflow shouldn't be compulsory.

It seems to be [some kind of trick](http://stackoverflow.com/questions/14164610/requirejs-optional-dependency), but I didn't look at it very much to be honest.

I'll close the issue to keep a single open threat about it. (https://github.com/alvarotrigo/fullPage.js/issues/2250)

**Comment by c10854** [comment]
I try add this in webpack.config.js, and that work for me
```
new webpack.ProvidePlugin({
    IScroll: "fullpage.js/vendors/scrolloverflow.min"
})
```

**Comment by alvarotrigo** [comment]
@c10854 thanks for the info!!

**Comment by Jacodom** [comment]
@c10854 
 Hi, i've tried this solution but it's not working for me. Please, can you paste a bit more of your webpack.config.js file? Thanks!

**Comment by alvarotrigo** [comment]
This issue should get solved in the next release 2.9.5.
Hopefully a few weeks.

**Comment by Jacodom** [comment]
Awesome!! thank you very much! wonderful library :D

**Comment by wallyzielinski** [comment]
Any headway on this? So far I can't get the plugin to work with requireJS at all.

**Comment by alvarotrigo** [comment]
> I can't get the scrolloverflow plugin to work with requireJS at all.

Easy. Copy the content of scrolloverflow and paste it at the very top of the fullPage file. 
This way you'll solve it :)

You just need to make sure it loads before fullpage.js, and this way will do it.

**Comment by wallyzielinski** [comment]
@alvarotrigo Unfortunately, that doesn't work with RequireJS, I suspect because they are both exporting variables. When I try it, I get an error that `fullpage` is not a function. Also, it's not ideal for our workflow to have two third-party plugins hacked together in one file. We try to keep a clean directory. 

Thus far, our only solution has been to include the script on the page before require, but this is not in our best practice.

If you have an official fix coming for this, do let me know so we can clean things up. Thank you!

**Comment by alvarotrigo** [comment]
> If you have an official fix coming for this, do let me know so we can clean things up.

Not really. As detailed above, the issue is require.js using compulsory dependencies and not optional ones.

**Comment by alvarotrigo** [comment]
This should be fixed on the dev branch 2.9.5 where big changes have been done in the scrolloverflow.js file and the way it loads.

**Comment by Rogant** [comment]
@c10854 Works for me thanks! (Vue2 / Webpack)

**Comment by vinoth44** [comment]
After spending lot of time I have managed to fix this issue. 

config file
--------------------
var config = {
    paths: {
        "IScroll" :        "js/scrolloverflow.min",
        "fullpage":        "js/jquery.fullpage"
    }
};

my script file: 
----------------------------

define(["jquery", "IScroll", "fullpage"], function($,IScroll) {
    "use strict";
    
    $('.fullpage').fullpage();
});


fullpage.js
---------------------
/***** just changed the top section *****/

(function(global, factory) {
    'use strict';

    if (typeof define === 'function' && define.amd) {
        define(['jquery', 'IScroll'], function($, IScroll) {
          return factory($, IScroll, global, global.document, global.Math);
        });
    } else if (typeof exports === "object" && exports) {
        module.exports = factory(require('jquery'), global, global.document, global.Math);
    } else {
        factory(jQuery, global, global.document, global.Math);
    }
})(typeof window !== 'undefined' ? window : this, function($, IScroll, window, document, Math, undefined) {

**Comment by alvarotrigo** [comment]
Fixed in 2.9.5

**Comment by NicolasEhrhard** [comment]
Hello , I've got the version 2.9.5 and it's not fixed for me.

I've got the following error : 
Uncaught (in promise): ReferenceError: IScroll is not defined
ReferenceError: IScroll is not defined
    at scrolloverflow.min.js:14

**Comment by alvarotrigo** [comment]
Are you using the latest scrolloverflow.js version too? [version 0.0.2](https://github.com/alvarotrigo/fullPage.js/blob/master/vendors/scrolloverflow.min.js) ?

If you still have errors try [the dev version 0.0.3](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.min.js).

**Comment by pttsky** [comment]
I am using webpack and having the same issue. I manually copied scrolloverflow.js v0.0.3 from the `dev` branch.

```
import 'fullpage.js/vendors/scrolloverflow';
import 'fullpage.js';

$(document).ready(() => {
    $('#fullpage').fullpage({ /* ... */, scrollOverflow: true });
})

```

The result is error like: 
```
scrolloverflow.js:2392 Uncaught ReferenceError: IScroll is not defined
    at scrolloverflow.js:2392
    at scrolloverflow.js:2733
    at Object.<anonymous> (scrolloverflow.js:2734)
    at __webpack_require__ (bootstrap 2162fd49c11f037fb8f3:19)
    at Object.defineProperty.value (main.js:15)
    at __webpack_require__ (bootstrap 2162fd49c11f037fb8f3:19)
    at Object.<anonymous> (tether.js:1811)
    at __webpack_require__ (bootstrap 2162fd49c11f037fb8f3:19)
    at module.exports.ctor.super_ (bootstrap 2162fd49c11f037fb8f3:62)
    at bootstrap 2162fd49c11f037fb8f3:62
```

**Comment by pttsky** [comment]
Thank you Alvaro! 
I just did `yarn add iscroll` then put `import IScroll from 'iscroll'` in the very beginning of `vendors/scrolloverflow.js` and obviously the error has gone. 
But for now I will come with another solution for scroll overflow since I already have one library for smooth scrolling in my project.

**Comment by dante-blitz** [comment]
I am also using webpack and v2.9.5 and still having the same issue...

```
import 'fullpage.js/vendors/scrolloverflow';
import 'fullpage.js';
```

I get the same error as @pttsky.

Anyone managed to get this working?

**Comment by corsachriz** [comment]
Still doesn´t work for me with the latest Version of Fullpage and Scrolloverflow

```
requirejs.config({
	baseUrl: 'js',
	paths: {
		jquery: 'jquery-3.3.1.min',
		IScroll: 'scrolloverflow',
		fullpage: 'jquery.fullPage',
	},
	 shim: {
         slimscroll: {
               deps: ['jquery']
         },
         IScroll: {
               deps: ['jquery']
         },
         fullpage: {
               deps: ['IScroll']
         }
    }
});
```

and

```
define(['jquery', 'IScroll', 'fullpage'], function($,IScroll) {
		$('#fullpage').fullpage();	
});
```

causes

```
scrolloverflow.js:2393 Uncaught ReferenceError: IScroll is not defined
```

**Comment by davidjr82** [comment]
@chriz1984 for me it is working with 

`window.IScroll = require('./../vendor/iscroll/iscroll.js');`

hope this helps.

**Comment by minlare** [comment]
I solved this is webpack using the following config:
```
plugins: [
        new webpack.ProvidePlugin({
          $: 'jquery',
          jQuery: 'jquery',
          IScroll: 'iscroll'
        })
]
```

**Comment by c1moore** [comment]
I'm still getting this error with the most recent versions.  I tried the `ProvidePlugin`; however, it basically results in
```
(function(IScroll) {
  (function() {
    // Right here a different (local) IScroll is defined.
    function IScroll() { /*...*/ }
  })();

  (function() {
    // Right here the IScroll passed to IIFE defined by webpack is used.
    IScroll.prototype.onWheel = /*...*/;
  })();
})(IScroll);
```

Since you define IScroll on the window anyways, why don't you just do something like
```
var IScroll;

(function() {
  IScroll = function IScroll() {/*...*/};
})();

(function() {
  IScroll.prototype.onWheel = /*...*/;
})();
```

This should work in just about any environment (Require.js, Webpack, non-AMD/UMD).

**Comment by alvarotrigo** [comment]
> why don't you just do something like

@c1moore please feel free to provide a pull request for it if you think that's a solution.

**Comment by mrG0bliN** [comment]
Uncaught TypeError: Cannot set property 'wheelOn' of undefined

**Comment by rafaelmagalhaes** [comment]
@mrG0bliN did you manage to solve that error ?

**Comment by VladlenTsoy** [comment]
> webpackProvidePluginConfig = {
		'$': 'jquery',
		'jQuery': 'jquery',
		'window.jQuery': 'jquery',
		'owl.carousel': 'owl.carousel',
		'IScroll': 'fullpage.js/vendors/scrolloverflow.min', (DELETE)
	},

**Comment by VladlenTsoy** [comment]
`webpackProvidePluginConfig = {
		'$': 'jquery',
		'jQuery': 'jquery',
		'window.jQuery': 'jquery',
		'owl.carousel': 'owl.carousel',
		'IScroll': 'fullpage.js/vendors/scrolloverflow.min', (DELETE)
	},`
Delete this "IScroll': 'fullpage.js/vendors/scrolloverflow.min" and code is work

**Comment by urbantrout** [comment]
@minlare This seems to work. Thanks!

**Comment by orbanisti** [comment]
> @chriz1984 for me it is working with
> 
> `window.IScroll = require('./../vendor/iscroll/iscroll.js');`
> 
> hope this helps.

this one works, thanks
