### ISSUE TITLE
Lazy load for picture element/srcset/sizes

### ISSUE THREAD

**Issue by EarlofArgyle** [alvarotrigo/fullPage.js#2355]
Hi,

is it possible to add support for srcset and sizes for responsive images using the `<img>` or `<picture>` element?

Best regards
David

**Comment by alvarotrigo** [comment]
I guess you can do that using media queries? What exactly is the issue?

**Comment by EarlofArgyle** [comment]
It's about lazyloading the images. By using srcset="" and sizes="" the browser looks for the best image size and loades the image immediately. This mechanism is executed although fullpage.js is set to lazyload the images via data-src.

**Comment by alvarotrigo** [comment]
@EarlofArgyle why can't you just do the following? 

    <img data-src="small.jpg" srcset="medium.jpg 1000w, large.jpg 2000w" />

**Comment by EarlofArgyle** [comment]
@alvarotrigo because the browser immediately looks for the best fitting image (in the srcset) and loads it, ignoring the data-src attribute and the lazy load technique in the script and creates an own src attribute. The lazy loading has NO effect. It's even bad, because the image, which was chosen by the browser, got overwritten with the one defined in data-src. It's a problem with <img> and <picture>/<source> element as well.

**Comment by alvarotrigo** [comment]
Is there any lazy loading library you know that deals with this issue?

**Comment by EarlofArgyle** [comment]
Yeah this one https://github.com/aFarkas/lazysizes. But i would rather try to use only one library (fullsize.js). Lazysizes calculates the sizes attribute as well, but its not really performant, certainly not if you have a lot of images in your longpage. It monitors the page for changes via CSS/JS or scrolling which is not necessary for fullpage, because you have your own triggers.

**Comment by EarlofArgyle** [comment]
Hey there,

do you have any news? Maybe I can contribute a solution to your project. I can try a simple solution with data-sizes and data-srcset and test it in different browsers.

Best regards
David

**Comment by alvarotrigo** [comment]
No updates I'm afraid. Didn't have time to look into it. Feel free to provide a pull request if you find a solution.

**Comment by alvarotrigo** [comment]
Fixed in the dev branch 2.9.4

**Comment by alvarotrigo** [comment]
Fixed in the latest release 2.9.4

**Comment by ibrokemypie** [comment]
any chance you could give a quick explanation of this? i want able to get it working in my brief testing...

_Sent from my HTC MSM8996 for arm64 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by alvarotrigo** [comment]
See the docs regarding the [lazy loading technique](https://github.com/alvarotrigo/fullPage.js#lazy-loading).

**Comment by ibrokemypie** [comment]
It doesnt seem to mention how to lazy load with <picture> tags, as data-srcset doesnt seem to work

**Comment by alvarotrigo** [comment]
@ibrokemypie `data-srcset` [should be working](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1618). 
Please make sure to use the latest fullpage.js version 2.9.4

**Comment by ibrokemypie** [comment]
can confirm it is not working on firefox nightly with version 2.9.4
Provided data-srcsets for jpg and png, and set the <img> src to a webp which firefox does not support, no image shows. Remove the data- prefixes and it works fine.

**Comment by alvarotrigo** [comment]
@ibrokemypie Can you please provide an isolated reproduction of the issue in jsfiddle or codepen?

**Comment by ibrokemypie** [comment]
@alvarotrigo https://jsfiddle.net/ibrokemypie/xmbguzt3/7/
obviously I wouldnt be using flif as the base image source, but I used that as the example since falling back to that wont work on any browser, therefore the image will only show if the sources are utilized.

**Comment by alvarotrigo** [comment]
@ibrokemypie yeah I see. That's because you are not using `<img data-srcset` but instead using `<source data-srcset` .
Feel free to open a new issue for this.

**Comment by BenRacicot** [comment]
Hey @alvarotrigo I was confused about this as well and wasnt able to find the documentation for the proper picture element's <img> src.

However, I did notice that the image for my footer section is still loading on page load (in dev tools Network tab). I was able to replicate that lazy loaded images below the top fold do load with the page here: [codepen.io/BRacicot/pen/JpLmqo](https://codepen.io/BRacicot/pen/JpLmqo?editors=1010) I must be doing something wrong, could you take a look?

Thanks as always.

**Comment by alvarotrigo** [comment]
@BenRacicot this is a bug that [has been solved](https://github.com/alvarotrigo/fullPage.js/commit/f35909eb3a41d36b9587cbcbdcaa28b54ca0d20d#diff-4b504794cf0b1577cc1134e09be6916d) in the [development version](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js).
Feel free to use that one until it is merged into a new release.

**Comment by BenRacicot** [comment]
Hey @alvarotrigo this dev version works! However where I am using fullpage-extensions the error persists. Is there an updated version of the extensions file?

**Comment by alvarotrigo** [comment]
> Is there an updated version of the extensions file?

There will be a major release next week. Version 3 of fullpage.js, which gets rids of jQuery!
The issue should be fixed there in both files.
