### ISSUE TITLE
-webkit-overflow-scrolling:touch is not working anymore (since 2.8.8)

### ISSUE THREAD

**Issue by thisisfed** [alvarotrigo/fullPage.js#2372]
**Link to isolated reproduction with no external CSS / JS**
https://jsfiddle.net/0hLzxrea/76/ — 2.8.8 (NOT WORKING)
https://jsfiddle.net/0hLzxrea/78/ — 2.8.7 (WORKING)

**Steps to reproduce it**
If you try to scroll the text inside the white box (first link) it won't scroll. 

**Versions** 
iPhone 6s iOS 10.1.1

**Comment by alvarotrigo** [comment]
Related with [this question in stackoverflow](http://stackoverflow.com/questions/10238084/ios-safari-how-to-disable-overscroll-but-allow-scrollable-divs-to-scroll-norma) and this issue https://github.com/alvarotrigo/fullPage.js/issues/2285

I'll mark it as a bug but won't have a solution soon. I would recommend you to use iScroll (or the fork included in fullpage.js (scrolloverflow.min.js)) to avoid those problems.
Also, not quite sure about the support of `-webkit-overflow-scrolling` in other browsers and devices.

**Comment by thisisfed** [comment]
I think it works now.

I modified this part like by adding 

> !checkParentForNormalScrollElement(event.target) &&

 

        /*
        * Preventing bouncing in iOS #2285
        */
        function preventBouncing(event){
            var e = event.originalEvent;
            if(!checkParentForNormalScrollElement(event.target) && options.autoScrolling && isReallyTouch(e)){
                event.preventDefault();
            }
        }

**Comment by alvarotrigo** [comment]
@thisisfed sounds like a possible solution! Thanks for it I'll take a look at it for the next release.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.8.9

**Comment by alvarotrigo** [comment]
Fixed in fullpage.js 2.8.9

**Comment by thisisfed** [comment]
I think this was not fixed on the Fullpage extension JS. I can't check properly cause it's minified.
