### ISSUE TITLE
Section height issue when using scrollOverflow + paddingTop

### ISSUE THREAD

**Issue by jorditarrida** [alvarotrigo/fullPage.js#2703]
Hi,
First of all thanks for your work on this library 🙂 . I have an issue I would need your help on.

### Description
I have a layout with a fixed header and  `scrollOverflow: true`. When I resize the window, the sections which are taller than the viewport (where scrollOverflow gets activated) get an incorrect CSS height value, thus causing layout problems. The incorrect values are also set if I trigger manually `$.fn.fullpage.reBuild()`.

### Link to isolated reproduction

I tried to isolate the code to the bare minimum but keeping some of the options I have set (such as `sectionSelector: '.page-section'` ) just in case the issue might be caused by these options.

On JSFiddle.net
http://jsfiddle.net/jorditarrida/0hnfumxj/1/

### Steps to reproduce it
1. Visit my JSFiddle http://jsfiddle.net/jorditarrida/0hnfumxj/1/
2. Check that the second section is higher than the viewport, scroll works fine, so does the library.
3. Scroll back up to section one.
4. Resize the window.
5. Scroll down to section two. The content now starts 60px lower than it should (where 60px is the header height), so the layout is broken 😞 .<br><img width="309" src="https://cloud.githubusercontent.com/assets/4738498/25967426/5bc80a10-368e-11e7-970f-6adaa42c3c5f.png">
6. When inspecting the elements, the second section has a `height` CSS attribute 60px lower than the others. The assigned height is the same of the inner `.fp-scrollable`. The value would be correct for the `.fp-scrollable` element, but the correct height for the `.page-section` element should be +60px.<br><img width="330" src="https://cloud.githubusercontent.com/assets/4738498/25967692/45a9e518-368f-11e7-9957-f9444a5fb4fb.png">

### Versions
I'm using the current version of your library (2.9.4). I've seen this issue on the latest versions of Chrome, Safari and Firefox for macOS.

Thanks in advance for your help,
Jordi

**Comment by alvarotrigo** [comment]
Use the `paddingTop` option instead of your own css `padding-top: 60px;`.
That should fix it.

Or better, if you want to keep using your own css, then add a container within the section and add the padding to it, not directly to the section.

```html
<div class="section">
    <div class="container">
         CONTENT HERE
    </div>
</div>
```

```css
.container{
   padding-top: 60px;
}
```

**Comment by jorditarrida** [comment]
Hey @alvarotrigo,
Thanks for your quick reply. 

I already tried using the fullPage.js `paddingTop` option, but the issue remains exactly the same. You can see it in this JSFiddle: http://jsfiddle.net/jorditarrida/nha7vv00/1/, the reproduction steps are exactly the same as in the previous example. So I still think this is an important issue that needs to be fixed.

The second method you provide is the one I'm currently using while I wait for the issue to be solved. I have created a new JSFiddle with it: http://jsfiddle.net/jorditarrida/ekypw8s1/1/ The problem with this option is that the `.fp-scrollable` container starts right at the top of the window, behind the `.header` bar, so some of the `.iScrollVerticalScrollbar` is hidden behind the header.

<img width="183" alt="captura de pantalla 2017-05-12 a les 10 28 21" src="https://cloud.githubusercontent.com/assets/4738498/25989887/10e13c7c-36fe-11e7-88fc-41725cc86a9d.png">

I've tried playing with `z-index` to solve this issue (I wouldn't mind the scrollbar overlapping the header, as long as it is not behind it), but I cannot seem to fix it due to the DOM reordering by the library and `position: fixed` vs `absolute`. Any tips on this?

Thanks again for your help,
Jordi

**Comment by alvarotrigo** [comment]
Right. somethings wrong then!
I'll mark it as a bug and take a look for the next release.

**Comment by alvarotrigo** [comment]
This issue was later opened again in here: https://github.com/alvarotrigo/fullPage.js/issues/3050

The bug has been fixed:
http://jsfiddle.net/0hnfumxj/2/

**Comment by alvarotrigo** [comment]
The fix will be released in fullPage.js 2.9.6
