### ISSUE TITLE
data-srcset in picture source tags doesn't work

### ISSUE THREAD

**Issue by ibrokemypie** [alvarotrigo/fullPage.js#2865]
### Description
Using data-srcset in the source tags of picture tags does not work.

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net or codepen.io, links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]
https://jsfiddle.net/ibrokemypie/xmbguzt3/7/

### Steps to reproduce it
Create a picture tag
Define sources with data-srcset values
Make the img tag's data-src value incorrect to force browser to load the source tags.
No image shows.
Removing the data- prefix in the source tags allows this to work as expected.

### Versions 
Tested on Chrome dev, firefox nightly and safari on macOS sierra.

**Comment by alvarotrigo** [comment]
Fixed on the dev branch 2.9.5

**Comment by ibrokemypie** [comment]
On 2.9.5 this issue still exists, at least on firefox.
Have updated the fiddle since the flif no longer exists, meaning that on chrome the webp fallback will show on both examples. If you test on another browser that does not support webp, you will see the first example (using data-srcset) does not attempt to load any other formats, but the second example (without the data- prefix) works as expected

https://jsfiddle.net/xmbguzt3/11/

**Comment by alvarotrigo** [comment]
True! Thanks for reporting it!
`data-src` works but not `data-srcset`.

Missing here:
```
 panel.find('img[data-src], img[data-srcset], source[data-src], video[data-src], audio[data-src], iframe[data-src]').each(function(){

```

**Comment by alvarotrigo** [comment]
Fixed "again"  in the dev branch 2.9.6
