### ISSUE TITLE
"getPaddings is not defined" in scrolloverflow.js after resize

### ISSUE THREAD

**Issue by arthurdewolf** [alvarotrigo/fullPage.js#3095]
I'm using fullPage (2.9.6) with scrollOverflow (5.2.0) and am getting the error `getPaddings is not defined` after resizing the window.

I was able to fix it by moving the `getPaddings` function out of and above the `scrollBarHandler` function.

**Comment by alvarotrigo** [comment]
> I'm using fullPage (2.9.6) with scrollOverflow (5.2.0) and am getting the error getPaddings is not defined after resizing the window.

The issue was fixed [here](https://github.com/alvarotrigo/fullPage.js/pull/3084) thanks to @Odrin that detected it. 

Make sure to use [the unminified version of the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js). (you can minifiy it yourself if you wish, just not updated in the dev branch)

**Comment by AbdulkaderTahhan** [comment]
I'm take the fixed file and update it successfully, but this error still exist i don't know what can i do for that,
thanks a lot

**Comment by alvarotrigo** [comment]
@AbdulkaderTahhan you'll have to provide an isolated reproduction of it in jsfiddle or codepen to prove it.

**Comment by AbdulkaderTahhan** [comment]
Here the example for this issue http://websitk.com/public/main/, 
i use this file https://goo.gl/mtGNBk but when click F12 on the browser you will find this error

**Comment by alvarotrigo** [comment]
@AbdulkaderTahhan your reproduction is not isolated. So it is not valid for me to check.
And, as I said, you should be using the file from the [dev folder](https://github.com/alvarotrigo/fullPage.js/blob/dev/vendors/scrolloverflow.js).

**Comment by petebarr** [comment]
Greetings!

Yeah, unfortunately, I'm getting the same issue when using the un-minified/minified cdn version. This example is pretty isolated: https://codepen.io/petebarr/pen/9dfa27828a12af469bf67da410346d09

Cheers!

**Comment by alvarotrigo** [comment]
@petebarr see my comment above yours. You should be using the dev version as the change was not yet merged into any public release. You are not using the dev version. Use the link i posted.

**Comment by petebarr** [comment]
May sound like a dumb question but is that the dev version of fullscreen.js or scrolloverflow.js?
Thanks again!

**Comment by alvarotrigo** [comment]
Use the latest of both. You'll get less bugs this way ;)

**Comment by petebarr** [comment]
Thanks, that works in Codepen now using the following URLs in "Add External Scripts/Pens":

https://rawgit.com/alvarotrigo/fullPage.js/dev/vendors/scrolloverflow.js
https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/jquery.fullpage.js

Appreciate it!

**Comment by mexn** [comment]
Hey,

are there any plans, when this fix will be available over npm?

**Comment by alvarotrigo** [comment]
@mexn soon! In the next release. Hopefully by the end of this week!

**Comment by mexn** [comment]
That's great news, thanks!

**Comment by alvarotrigo** [comment]
@mexn I've just published the new release 2.9.7!

**Comment by alvarotrigo** [comment]
@hortonelectric please provide an isolated reproduction. Working as expected on the [demo page](https://alvarotrigo.com/fullPage/examples/scrolling.html).

**Comment by alvarotrigo** [comment]
@hortonelectric ok, I've noticed I forgot to update the minified version. The unminified one should work as expected. Merging the minified one now, but you won't get it on npm. So please get it from here until the next release gets pushed to npm.  https://github.com/alvarotrigo/fullPage.js/pull/2907
