### ISSUE TITLE
OrientationChange on Slides breaks Layout on Chrome (mobile)

### ISSUE THREAD

**Issue by zwickmueller** [alvarotrigo/fullPage.js#3336]
### Description

When you change the orientation of your phone on a section with slides, the sections are not fullscreen anymore, when you change back to portrait orientation.
I thought it was connected with scrolloverflow: true, but it does happen without it, too.
See Link below and follow steps to reproduce.

### Link to isolated reproduction with no external CSS / JS
http://arturneufeld.com/clients/temp/orientationchangeissue

### Steps to reproduce it
1. On mobile, scroll to Section 2, the one with slides
2. Tilt phone to landscape and back to portrait
3. The sections are not fullscreen anymore, the layout is divided (50% of viewport, instead of 100%)
4. To verify: refresh, repeat step on section 1 -> no issue. Repeat step on section 3 -> same issue as on section 2 

### Versions 
Iphone 6, the issue only appears on Chrome. Safari works.

**Comment by alvarotrigo** [comment]
Thanks for reporting it!!
I'll take a look  at it!

**Comment by alvarotrigo** [comment]
I'm not quite sure if this is due to [this Chrome bug](https://bugs.chromium.org/p/chromium/issues/detail?id=833440&can=2&start=0&num=100&q=window.innerWidth&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=) as was pointed out on [this Three.js discussion](https://github.com/mrdoob/three.js/issues/12988).

It seems fullPage.js gets the wrong value here on [line 3367](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js#L3367).

Currently the latest Chrome version for iPhone is version 68. So I'll wait until version 69 to see if that fixes the issue.

**Comment by izabelanc** [comment]
Hi @alvarotrigo,

We're now on Version 70.0 of Chrome on iOS, and the issue still there.

Can this be rectified?

Thanks a lot!

**Comment by alvarotrigo** [comment]
@izabelanc please check the dev version now. I think I've fixed it adding an ugly little timeout. (didn't find any [better and simple option](https://stackoverflow.com/questions/12452349/mobile-viewport-height-after-orientation-change))

**Comment by alvarotrigo** [comment]
Now fixed in fullPage.js 3.0.4!

**Comment by izabelanc** [comment]
Hi @alvarotrigo ,
Unfortunately, it is still happening on iOS Chrome, even on fullPage.js 3.0.4.

Can you please have a look?

Thank you!

**Comment by izabelanc** [comment]
Also, when scrolling on iOS Chrome between pages, it's very jumpy.

Whereas in Safari has a super nice and smooth transition. 

Thanks

**Comment by alvarotrigo** [comment]
> Unfortunately, it is still happening on iOS Chrome, even on fullPage.js 3.0.4.

I can not reproduce it on the [demo page](https://alvarotrigo.com/fullPage/) using iOS Chrome. Which iOS version are you using?

> Also, when scrolling on iOS Chrome between pages, it's very jumpy.

I can neither reproduce it on any of the examples pages like [the vertical navigation one](https://alvarotrigo.com/fullPage/examples/navigationV.html).

It sounds to me like the issue might be because your phone might be quite slow? Then the timeout I added to solve this issue might not be enough for your phone?

You can try changing this line:

```javascript
                        }, navigator.userAgent.match('CriOS') ? 50 : 0);
```

For this one:
```javascript
                        }, navigator.userAgent.match('CriOS') ? 150 : 0);
``` 

And if it still not working try increasing the value even more. 200, 300 ...

**Comment by izabelanc** [comment]
Hi Alvaro,

Thanks for your message.

I’m on an iPhone XS Max, don’t think that’s the issue and on the latest
iOS. The smooth scrolling is fine on an iPhone 6 using Chrome.

The 50% screen tilt bug still present on both iPhones mentioned here.

Thanks

**Comment by alvarotrigo** [comment]
Alright, I've just tested iPhone XS Max on Browserstack. 
Is this the issue you are facing? See the gift below.
![iphone](https://user-images.githubusercontent.com/1706326/49937780-2ad82700-fed8-11e8-8e1e-fb9a4cd9adfd.gif)
More than a break of the layoug, the change of section?

**Comment by izabelanc** [comment]
Hi,
Please see the screen recording below:
https://we.tl/t-7cQBZt1wcE

Thanks!

**Comment by alvarotrigo** [comment]
Can you please add a video with the [demo page instead](https://alvarotrigo.com/fullPage/)?

**Comment by izabelanc** [comment]
Sure, here it is:
https://we.tl/t-9ms54jEkyR

Thanks

**Comment by izabelanc** [comment]
Hi,
Tried 150, was a bit smoother, then to 300 and it made it super jumpy.

Although, the 50% screen bug still persists.

Thanks

**Comment by alvarotrigo** [comment]
I'll reopen the issue to try to check it again for the next release.

**Comment by notcarbide** [comment]
Re: https://github.com/alvarotrigo/fullPage.js/issues/3336#issuecomment-446946343 & Closed issue this was referenced to.

I'm not sure if there is a fix-all elegant solution for this because of the way FullPage is by default. A possible solution (using a site with something persistent [header,footer, etc.] https://alvarotrigo.com/fullPage/ as an example) is to move the header outside of the FullPage instance and create a wrapper for FullPage. From there you can work out some CSS like this: https://github.com/carbideband/carbideband.github.io/commit/f2f4a6a84655889f993121fdb8c73584d10c6eb4
Having fp-slides height at 100% seems to cause the slide to be the size of the ViewPort, which on a landscape mobile device can be very thin. It's also likely that you'll want things like autoScrolling and fitToSection set to false, so the sections that do not fit are still scrollable.
YMMV depending on your FullPage usage, but this works for mine. Cheers!

**Comment by ofsahinler** [comment]
Hello there.I'm having the same problem.
I'm looked at the problem a little. I added the test videos made on iPad Pro 12"(2. generation)(ios 12.2) and iPad Air 9.7"(2017-ios 11.4.1).

[https://we.tl/t-uAzSVVfUMI](url)

**Comment by dwmChris** [comment]
Hi,

changing the orientation on iOS Chrome and Firefox from horizontal back to vertical still destroys the layout. This is can be reproduced on some of your demo pages. (Responsive, Full Backgrounds, Fixed Header and Footer and others) Any updates on that issue?

Cheers

**Comment by alvarotrigo** [comment]
@dwmChris @ofsahinler @notcarbide  thanks for reporting it!
I believe I've finally managed to fix it with a kind of hacky solution.

The issue is that Chrome fires the resize event before actually finishing the readjustment of the page, while it is animating, and therefore it is still reporting the previous viewport dimensions at that point.

Please feel free to replace your current fullPage.js file for [this one on the dev branch](https://github.com/alvarotrigo/fullPage.js/blob/dev/src/fullpage.js) and let me know if  it fixes the issue for you.

I'll merge it for the next release 3.0.6 in about a week.

**Comment by dwmChris** [comment]
@alvarotrigo Thank you, this fixed the issue in Chrome on iOS. Firefox on iOS still has the same error though.

**Comment by alvarotrigo** [comment]
> Firefox on iOS still has the same error though.

Uh! I didn't notice you also talked about Firefox. In that case, please try again with the latest file.
I've made it so it will behave the same way for all browsers now.

**Comment by dwmChris** [comment]
@alvarotrigo Perfect! Problem solved. Thank you!
