### ISSUE TITLE
Flickering error on Google Chrome 73

### ISSUE THREAD

**Issue by iochoaveiss** [alvarotrigo/fullPage.js#3600]
In Google Chrome 73, latest release, fullpage flickers when doing the scroll. In addition, in console we can also see the following error:

`
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
we @ fullpage.min.js?34874:sourcemap:11
Pt @ fullpage.min.js?34874:sourcemap:11
`

### Example
The issue can be reproduced in the scrollBar example, provided with the library.

### Versions 
Browser: Google Chrome 73.0.3683.75 (released on March 15th 2019)

**Comment by arsik** [comment]
Small hack. It doesn't work perfectly but better than without it.

`function preventDefault(event){
      if(event.preventDefault){
          // event.preventDefault();
          // event.returnValue = true;
          if (!document.body.classList.contains('animated')) {
              document.body.style.overflow = 'hidden';
              document.body.classList.add('animated');
              setTimeout(function () {
                  document.body.style.overflow = 'auto';
                  document.body.classList.remove('animated');
              }, 700);
          }
      }
      else{
          event.returnValue = false;
      }
  }`

**Comment by iochoaveiss** [comment]
> 
> 
> Small hack. It doesn't work perfectly but better than without it.
> 
> ```
> function preventDefault(event){
>       if(event.preventDefault){
>           // event.preventDefault();
>           // event.returnValue = true;
>           if (!document.body.classList.contains('animated')) {
>               document.body.style.overflow = 'hidden';
>               document.body.classList.add('animated');
>               setTimeout(function () {
>                   document.body.style.overflow = 'auto';
>                   document.body.classList.remove('animated');
>               }, 700);
>           }
>       }
>       else{
>           event.returnValue = false;
>       }
>   }
> ```

Sorry, I'm quite new to the library. What should I do with this code?

**Comment by alvarotrigo** [comment]
@iochoaveiss  Thanks for reporting it! Looks ugly indeed!
I'll take a look at it!

**Comment by arsik** [comment]
@iochoaveiss you need to find and replace this function in library or you can do it when author of this lib will fix it himself

**Comment by iochoaveiss** [comment]
@arsik thanks for the answer. I think I will wait for an official solution.

**Comment by alvarotrigo** [comment]
I've fixed the issue on the [dev branch 3.0.5.](https://github.com/alvarotrigo/fullPage.js/tree/dev/dist).

It will get merged in the next release.

**Comment by iochoaveiss** [comment]
@alvarotrigo Thank you so much. The flickering is now solved.

**Comment by alvarotrigo** [comment]
No problem! 😉

**Comment by deepfriedfilth** [comment]
@alvarotrigo I believe this issue is still affecting fullpage instances if `lockAnchors` option is not **explicitly set** to `true` even using latest 3.0.5 from dev branch

These were my options prior, that resulted in jumping down 3 sections prior to every vertical/section move (destination would still work as intended)
```
sectionSelector: 'section',
scrollBar: true,
controlArrows: false,
autoScrolling: true,
verticalCentered: false
```
Note: Adding `lockAnchors: false,` to above list still results in jumpy behavior

**Comment by alvarotrigo** [comment]
@deepfriedfilth I'm not able to reproduce your issue. 
Can you reproduce it on the [scrollbar example page](https://alvarotrigo.com/fullPage/examples/scrollBar.html). That's using by default `lockAnchors:false`.

**Comment by deepfriedfilth** [comment]
@alvarotrigo seems to be resolved when I pull in latest dev version of JS (3.0.5) to the scrollbar example page...

Could've just been a cache hiccup, I suppose. ¯\\\_(ツ)\_/¯
Will try to rebuild exact conditions to test and report back if able to reproduce.

**Comment by SulphurDioxide** [comment]
I found this solution via #2362 which looks to be the same issue except now this feature is [enabled by default](https://www.chromestatus.com/features/6662647093133312) in Chrome 73.

**Comment by alvarotrigo** [comment]
@SulphurDioxide the issue has been solved so nothing to worry about now :)

**Comment by n0umankhan** [comment]
@alvarotrigo dude I can see this issue still exists in react-fullpage can we update fullpage js there as well?

**Comment by n0umankhan** [comment]
for a temporary fix we can use below code:

`window.addEventListener(
      'wheel',
      event => {
        event.preventDefault();
      },
      { passive: false }
    );`

**Comment by Tm7474** [comment]
#3600

**Comment by alvarotrigo** [comment]
@n0umankhan thanks for the heads up!
I've updated the extensions file on the react wrapper too. Please use the [dist files from the dev branch](https://github.com/alvarotrigo/react-fullpage/tree/dev/dist).

I'll merge them into the master next week when I publish fullPage.js 3.0.5.

**Comment by alvarotrigo** [comment]
This issue has been fixed in the latest fullPage.js release 3.0.5!

**Comment by n0umankhan** [comment]
@alvarotrigo hi release is published now?

**Comment by alvarotrigo** [comment]
Yes

**Comment by alvarotrigo** [comment]
You can always check it in the docs on the top left where the version number is displayed.
![image](https://user-images.githubusercontent.com/1706326/56034736-7684cb00-5d28-11e9-9213-9a24604dc758.png)

**Comment by n0umankhan** [comment]
Thank you for the help and kindness, I'm not sure what's wrong here I'm still facing same error in my react-app

**Comment by alvarotrigo** [comment]
Make sure to update to the latest [react-fullpage](https://github.com/alvarotrigo/react-fullpage) version 0.1.14

**Comment by alvarotrigo** [comment]
If you check the [online demo](https://alvarotrigo.com/fullPage/examples/scrollBar.html) you'll notice the error doesn't take place there anymore. 
Make sure you are not caching the JS files.

**Comment by n0umankhan** [comment]
Hurray Thanks it works now with 0.1.14

**Comment by engerguedez** [comment]
Hi, I have a problem.

When you are scrolling up, it does not take the entire section. Somebody could help me?

**Comment by alvarotrigo** [comment]
> When you are scrolling up, it does not take the entire section. Somebody could help me?

Please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code. Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).
