### ISSUE TITLE
Error code when using normalScrollElements option and leave mouse point from browser window to debug console.

### ISSUE THREAD

**Issue by CressZZ** [alvarotrigo/fullPage.js#3931]
### Description
Hi.
I saw follow error code when i use `normalScrollElements` option and leave mouse point from browser window to debug console.
```
scrolloverflow.js:2412 Uncaught TypeError: Cannot read property '0' of null
    at Object.setIscroll (scrolloverflow.js:2412)
    at HTMLDocument.onMouseEnterOrLeave (fullpage.js:766)
```
Actually i think that it may be occurred from `function onMouseEnterOrLeave(e)` in  fullpage.js.

```js
        function onMouseEnterOrLeave(e) {
            // ...

            //onMouseLeave will use the destination target, not the one we are moving away from
            var target = type === 'mouseleave' ? e.toElement || e.relatedTarget : e.target;

            if(target == document || !target){
                setMouseHijack(true);

                if(isUsingScrollOverflow){
                    options.scrollOverflowHandler.setIscroll(target, true);
                }
                return;
            }

            // ...
        }
```
 
Because when i leave mouse point from browser window to debug console, 
1. eventType is `mouseleave`.
2. event.toElement is `null`.

and then  `options.scrollOverflowHandler.setIscroll(target, true);`   in `scrollOverflow.js` is occur error because target is null.
 
`var scrollable = fp_utils.closest(target, SCROLLABLE_SEL) || $(SCROLLABLE_SEL, target)[0];`

```js
 /* scrollOverflow.js */

            // Enables or disables the whole iScroll feature based on the given parameter.
            setIscroll: function(target, enable){
                if(!iscrollHandler.hasBeenInit){
                    return;
                }
                var scrollable = fp_utils.closest(target, SCROLLABLE_SEL) || $(SCROLLABLE_SEL, target)[0];
                var action = enable ? 'enable' : 'disable';
                
                if(scrollable){
                    scrollable.fp_iscrollInstance[action]();
                }
            }

```
So, could you check this matter..

sorry for my writing issue skill. it's my first issue...

Ah!! and i know that this is minor issue to user not developer. they would not see this error. 

### Link to isolated reproduction with no external CSS / JS
[Ideally in jsfiddle.net (https://jsfiddle.net/alvarotrigo/ea17skjr) or codepen.io (https://codepen.io/alvarotrigo/pen/NxyPPp), links to personal websites won't be reviewed unless isolated. Reported issues without a reproduction might get closed.]

### Steps to reproduce it
1. Using normalScrollElements
2. Leave mouse point from browser window to debug console.

### Versions 
fullPage 3.0.8

**Comment by alvarotrigo** [comment]
Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.

Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).

**Comment by CressZZ** [comment]
@alvarotrigo 

> Can you please provide an isolated reproduction in [jsfiddle](https://jsfiddle.net/alvarotrigo/ea17skjr/) or [codepen](https://codepen.io/alvarotrigo/pen/qqabrp), with no CSS or JS files external to fullPage.js and the minimum amount of HTML code? Use empty sections unless strictly necessary for the reproduction.
> 
> Perhaps you might find useful to read my article regarding [how to create isolated reproductions](https://alvarotrigo.com/blog/how-not-suck-at-asking-coding-questions/).


Thank you for your reply.
First of all, this error cannot be fully reproduced in `jsfiddle` or `codepen`. Because in that case, the iframe will cover the document element.(This error should be occurred when mouse cursor leave form the document element to a `null` as out of browser or debug window.)

But, I tried it once making reproduction with [codepen](https://codepen.io/cress00/pen/WNvaQaN) (https://codepen.io/cress00/pen/WNvaQaN) based on you codepen of demo for [normaloverflowscroll](https://codepen.io/alvarotrigo/pen/RmVazM).


### Please refer to attached capture following codepen.(https://codepen.io/cress00/pen/WNvaQaN)
You can see increasing error message count when trigger mouseleave event from the document element to out of document element. 
 
![codepen](https://user-images.githubusercontent.com/25162881/77391476-2dfcdb00-6ddc-11ea-858d-f7adf0e510a6.gif)



### Additionally, I attach another capture that using above same code without codepen(no iframe).
You can see increasing error message count when trigger mouseleave event from the document element to out of document element. 
![화면 기록 2020-03-24 오후 2 29 39 mov](https://user-images.githubusercontent.com/25162881/77392706-e4fa5600-6dde-11ea-87f5-8454a432bf9c.gif)


### html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
<script src="https://unpkg.com/fullpage.js@3.0.8/dist/fullpage.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/3.0.8/vendors/scrolloverflow.js"></script>

</head>
<body>
  <div id="fullpage">
  <div class="section">
    Section 1
    <div class="scrollable-content">
      <h4>Scroll me</h4><h4>Scroll me</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4>
    </div>
  </div>
  <div class="section">
      <div class="slide" data-anchor="slide1">
        Slide 2.1
         <div class="scrollable-content">
      <h4>Scroll me</h4><h4>Scroll me</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4><h4>Text here</h4>
    </div>
      </div>
      <div class="slide" data-anchor="slide2">Slide 2.2</div>
  </div>
  <div class="section">Section 3</div>
  <div class="section">Section 4</div>
</div>
</body>
</html>
```
### css
```css
.section {
  text-align:center;
  font-size: 3em;
}
.scrollable-content{
  background: white;
  overflow: scroll;
  margin: 0 auto;
  width: 500px;
  height: 250px;
}
```
### js
```js
new fullpage('#fullpage', {
  sectionsColor: ['yellow', 'orange', '#C0C0C0', '#ADD8E6'],
  normalScrollElements: '.scrollable-content',
  scrollOverflow: true,
});
```

This error code is occurred when
1. Using `normalScrollElements` option. 
2. Using `scrollOverFlow` option being `true`.
3. Leaving mouse cursor to out of document element.

If you need more information or better reproduction or report please let me know. 
Thanks.

**Comment by alvarotrigo** [comment]
Thanks for reporting it! 👍 
We will take a look at it for the next release!

**Comment by eMtlk** [comment]
@alvarotrigo When is next release coming out? :)

**Comment by alvarotrigo** [comment]
@eMtlk hopefully by the end of this month! :)
I'm a bit busy these days, so I've been delaying it more than I want...

**Comment by RobertLang** [comment]
I know that it's still 5 days until the end of the month but we are also eager to get our hands on the new release ;-)

**Comment by alvarotrigo** [comment]
@RobertLang good to know :)

**Comment by alvarotrigo** [comment]
This issue was fixed in December 2019  in the dev branch. 
https://rawgit.com/alvarotrigo/fullPage.js/dev/vendors/scrolloverflow.js

I'll be merging this into the next release today.

**Comment by alvarotrigo** [comment]
Fixed in fullPage.js 3.0.9! 👍

**Comment by dianastanciu** [comment]
I still have this issue, even though using fullPage.js 3.0.8 + the updated scrolloverflow.js. Not quite sure what to do..

**Comment by rico** [comment]
@alvarotrigo this is still an issue in vue-fullpage.js

**Comment by alvarotrigo** [comment]
> @alvarotrigo this is still an issue in vue-fullpage.js

Feel free to open an issue on the [vue-fullpage.js](https://github.com/alvarotrigo/vue-fullpage.js) issues forum together with an isolated reproduction in codepen/codesandbox.
