### ISSUE TITLE
Activation Key Gutenberg

### ISSUE THREAD

**Issue by CarmenSommer** [alvarotrigo/fullPage.js#4148]
Activation Key Not working anymore (Extension for Gutenberg)

We activated the extension as stated in the doc. Worked perfectly, unfortunately after one moth the alert for "Unlicensed fullPage.js Extension" is back on our Page.

Here is the Link for the Website: http://www.alpinerei.de/site/

Is there a way to reset the activation in Gutenberg? 

Cheers,
Carmen

**Comment by alvarotrigo** [comment]
Can you please try again ?
It should be fixed :)

Thanks for reporting it and apologies for the inconvenience!

**Comment by CarmenSommer** [comment]
Hi, wow thanks for you quick reply!

Unfortunately the error is still there..
Gutenberg does not allow me to reconnect my activation key with the plugin.

Thanks for your support!

**Comment by alvarotrigo** [comment]
Nothing to worry about! 
The extension is activated but you haven't introduced the key (or the right one) on the wodpress panel.

See the docs regarding how to add the activation key on the WordPress plugin for Gutenberg:
https://www.meceware.com/docs/fullpage-for-gutenberg/#extensions

**Comment by CarmenSommer** [comment]
Hey, I guess I did, it even says the activation key is valid. But in the front end the error is still shown.

![Uploading Bildschirmfoto 2021-01-22 um 19.38.15.png…]()

**Comment by alvarotrigo** [comment]
Alright, please contact us via the [contact form](https://alvarotrigo.com/#contact).

**Comment by CarmenSommer** [comment]
Thanks for you support!
