### ISSUE TITLE
Enter Fullscreen in Mobile view? 

### ISSUE THREAD

**Issue by willblackburn** [alvarotrigo/fullPage.js#4342]
Hiya,

Sorry might be noobish question but In mobile view and on tablet i am unable to enter full screen mode {like when i push up it hides the tabs and url bar on android}.  Is that a Fullpage.js option i can change? 

Currently i am using Fullpage like this for sections - 

<div class="section about" data-anchor="aboutus">

And my options look like - 

```js
      new fullpage('#fullpage', {
        //options
        scrollBar: true,
        autoScrolling: true,
        scrollingSpeed: 1500,
        navigation: false,
        anchors: [
          'home',
          'aboutus',
          'services',
          'residential',
          'commercial',
          'gallery',
          'contact',
        ],
        controlArrows: false,
        slidesNavigation: true,
      })
```

Many thanks, 

Will

**Comment by alvarotrigo** [comment]
Disable the scrollbars by using `scrollBar: false`.
That should fix the issue by preventing the address bar to get hidden. 

On fullpage.js v4 this issue will probably go away.

**Comment by willblackburn** [comment]
> Disable the scrollbars by using `scrollBar: false`. That should fix the issue by preventing the address bar to get hidden.
> 
> On fullpage.js v4 this issue will probably go away.

Thanks Alvarotrigo. Tried what you suggested but still doesn't enter fullscreen mode in mobile. Only way i can currently do it is removing that entire script itself. 
 
I have changed my section's to this now if that makes any difference. 
<div
        class="section fp-auto-height-responsive about"
        data-anchor="aboutus"
      >

Cheers, W

**Comment by alvarotrigo** [comment]
Can you provide a video please?

**Comment by willblackburn** [comment]
I can't really as i only have a tablet and no other phone to record. Can send you over files though? I was looking at some other peoples example sites and they had the same behaviour on mobile.

**Comment by alvarotrigo** [comment]
> I was looking at some other peoples example sites and they had the same behaviour on mobile.

If your address bar gets hidden on the [demo page](https://alvarotrigo.com/fullPage/) and on the examples (like [this one](https://alvarotrigo.com/fullPage/examples/continuous.html)) then there's probably nothing we can do about it.

I personally can not reproduce the issue on my iPhone 11 in either Safari, Firefox, or Chrome. (Using iOS 15.4).
Scrolling up and down won't cause the scroll bar to disappear.  

I'm not able to reproduce the issue either on Android by using real devices on browserstack.com using a Samsung S22 with 12.0.
Demo attached.
https://user-images.githubusercontent.com/1706326/160381989-b0295b62-de23-4b34-a44c-86f3482252fb.mp4

**Comment by willblackburn** [comment]
I think we are getting cross wires. I WANT the URL and tabs to dissappear  {when you push up with your thumb on android it hides the url and tabs}. That's full screen mode. It works on most sites but FP seems to restrict it.

**Comment by alvarotrigo** [comment]
If you want it to disappear on scroll, then use `scrollBar: true`.
However, note the height of the sections won't update and you will see part of the next or previous section on the viewport.

This should get fixed in fullPage.js v4. But I'd probably recommend keeping the address bars visible if you want to prevent some glitches while the sections adapt to the new viewport size.

Note we developers have very little control over the address bar. The only way to get the default behavior is by enabling the scroll bar.

**Comment by SubZane** [comment]
I think it might be an issue when the address bar is in the bottom of the windows in IOS on iphone. The scrollbar true/false doesn't seem to make any difference. When the user scrolls the available screen height grows and shrinks depending on if the adress bar hides or not...

https://user-images.githubusercontent.com/90636/161012883-d633d518-0d45-4742-9f2a-d69426f3b29e.MP4

**Comment by alvarotrigo** [comment]
> maybe this is already an available setting that I missed or something.

fullPage.js takes care of that. You can see those styles being applied to both the BODY and the HTML element with inline styles:
<img width="837" alt="image" src="https://user-images.githubusercontent.com/1706326/161030703-c4d7d333-2557-4ded-8e1f-533150ed1400.png">

I've tried [this page](https://alvarotrigo.com/fullPage/examples/continuous.html) from my iOS 15 iPhone and I can't reproduce the issue in Safari.

However, I'm able to reproduce it on Browserstack.com. So this confuses me quite a lot.
Perhaps is an iOS config?

**Comment by alvarotrigo** [comment]
What iOS version are you using? I'm under 15.4.
The reproduction on Browserstack is under 15.1 (perhaps there was a safari bug back there?)

**Comment by SubZane** [comment]
ok, I just connected my iphone to my macbook for some debugging. It seems that there's nothing wrong with your script, but the HTML was missing 
```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
```
and as I added both my css and this markup at the same time I thought it was the css that fixed it. But it was the meta viewport!

**Comment by alvarotrigo** [comment]
> and as I added both my css and this markup at the same time I thought it was the css that fixed it. But it was the meta viewport!

So just to clarify it, you are not able to reproduce the issue on [this page](https://alvarotrigo.com/fullPage/examples/continuous.html) then?

**Comment by alvarotrigo** [comment]
> However, When I injected the meta viewport into the code, the url-bar stopped hiding when scrolling. So maybe you'll need to add the meta viewport? (I know that it will screw over all your css though)

What is weird is that I can not reproduce the issue on my iOS 15.4 on that same URL.
So it looks like some kind of change in Safari in the newest iOS?

**Comment by SubZane** [comment]
> What is weird is that I can not reproduce the issue on my iOS 15.4 on that same URL. So it looks like some kind of change in Safari in the newest iOS?

I guess we will never know :) At least we found a solution for the people experience the same error. Just add meta viewport 👍

**Comment by alvarotrigo** [comment]
Yeap, that's a good thing for sure! Thanks for that!! 👍

**Comment by SubZane** [comment]
No problem! Thanks for replying so quickly on this 👍

**Comment by alvarotrigo** [comment]
> Is that a Fullpage.js option i can change?

Now it is in fullpage.js 4.0.33! 🥳 

It's called `adjustOnNavChange`. It's explained in the docs:
https://alvarotrigo.com/fullPage/docs/#adjustonnavchange
