### ISSUE TITLE
interlockedSlides not working in 4.0.6

### ISSUE THREAD

**Issue by Cosirax** [alvarotrigo/fullPage.js#4368]
Thanks for the fast bugfix from my yesterday's issue!

With the new Update 4.0.6 the extension interlockedSlides is no longer working for me.
I can't provide more information yet if its necessary I can contribute more the next days.

Thanks in advance!

**Comment by alvarotrigo** [comment]
It should work once you introduce a valid `licenseKey`.
But thanks for reporting it!

Fixed on the dev branch 4.0.7.

**Comment by Cosirax** [comment]
Thanks for your answer. I've tested the dev branch but it's still not working in my dev environment. Unfortunatly I can't test it at the live environment yet were I've purchased the license for. Is it intended that the extension won't work until there is a valid license?

**Comment by alvarotrigo** [comment]
Are you using fullPage.js version 4?
Or just the version 4 for the interlocked slides extension?

**Comment by Cosirax** [comment]
I am using "fullpage.js Interlocked Slides Extension 0.1.0 for fullpage.js v4" and fullPage 4.0.7 from dev branch

**Comment by alvarotrigo** [comment]
> fullPage 4.0.7 from dev branch

The extension's files I'd assume?
https://rawgit.com/alvarotrigo/fullPage.js/dev/dist/fullpage.extensions.min.js

I can not reproduce the issue. 
Can you share with us your URL so we can inspect it?

You can use the [contact form](https://alvarotrigo.com/contact/) for that if you prefer. Use the email you used for the purchase.

**Comment by Cosirax** [comment]
I've sent you a mail via the contact form. Thanks in advance :)

**Comment by alvarotrigo** [comment]
Let's keep the converation there.
