### ISSUE TITLE
Auto Height Sections Minimum Height Issue on Dev Branch

### ISSUE THREAD

**Issue by meceware** [alvarotrigo/fullPage.js#4471]
Hi,

I would like to ask, there was no `min-height` attribute in [`.fp-auto-height`](https://github.com/alvarotrigo/fullPage.js/blob/3.1.2/dist/fullpage.css#L215) on the previous versions, but with the dev branch after `v4.0.11`, `min-height` attribute is added to `.fp-auto-height`.

I think this issue is related to [#4467](https://github.com/alvarotrigo/fullPage.js/issues/4467). In my opinion, overriding `min-height` with `!important` should not be there, it conflicts when users set the minimum height for auto height sections. When this is overridden, the height gets auto no matter what the user sets, which imho what's intended with auto height sections.

Thank you,

**Comment by meceware** [comment]
I think an option would be to divide these into two part as below:

```
/* Used with autoScrolling: false */
.fp-scrollable.fp-responsive .fp-is-overflow.fp-section,
.fp-scrollable .fp-section,
.fp-scrollable .fp-slide{
   /* Fallback for browsers that do not support Custom Properties */
   height: 100vh;
   height: calc(var(--vh, 1vh) * 100);
}

.fp-scrollable.fp-responsive .fp-is-overflow.fp-section:not(.fp-auto-height),
.fp-scrollable .fp-section:not(.fp-auto-height),
.fp-scrollable .fp-slide:not(.fp-auto-height){
    /* Fallback for browsers that do not support Custom Properties */
    min-height: 100vh;
    min-height: calc(var(--vh, 1vh) * 100);
}
```

**Comment by alvarotrigo** [comment]
> I think this issue is related to https://github.com/alvarotrigo/fullPage.js/issues/4467.

I think on this issue the user expects the `fp-overflow` element to take the height of the section, but that's not how it works right now. 
I believe that's an issue regarding the ScrollOverflow feature more than the `fp-auto-height`.


> In my opinion, overriding `min-height` with `!important` should not be there, it conflicts when users set the minimum height for auto height sections. When this is overridden, the height gets auto no matter what the user sets, which imho what's intended with auto height sections.

So, we are talking about when the developer decides to use `min-height` to set the height, right? 
Because if he uses `height`, he would also have to use ` !important` to overwrite the fullpage.js value for `fp-auto-height`.
Is this related in any way to WP plugins? 

This issue existed in version 3 in the same way as it does now as far as I'm concerned:

With v3.1.2:
https://codepen.io/alvarotrigo/pen/OJZGLBW

With v4.0.12 (dev branch)
https://codepen.io/alvarotrigo/pen/ZEoZzqM

I guess this wasn't a huge issue because the developer was just adding content to the section or use a wrapper inside to set the size. For example:

With v4.0.12 (dev branch) but using a container with fixed height
https://codepen.io/alvarotrigo/pen/VwxNZqL

**Comment by meceware** [comment]
> So, we are talking about when the developer decides to use min-height to set the height, right?

That's right! Especially on auto height sections. 

> Is this related in any way to WP plugins?

That's right! with WP plugins, `!important` (most probably) might not override the min-height set by fullpage. 

> This issue existed in version 3 in the same way as it does now as far as I'm concerned

I don't think this issue is seen on version 3.  The height has set with auto height sections on `fp-tableCell` but `min-height` does not on that element.

Thank you,

**Comment by meceware** [comment]
Hi,

Please find an CSS file updated version here:

https://www.meceware.com/wp/fullpage-for-elementor/test1/

If you could update `fullpage.min.css` file with the [dev latest version](https://raw.githubusercontent.com/alvarotrigo/fullPage.js/dev/dist/fullpage.min.css) via developer tools, you'd see the difference.

Thank you,

**Comment by alvarotrigo** [comment]
Is this difference the one you are referring to?

With v3.1.2 (Applying min-height on 2nd section)
https://codepen.io/alvarotrigo/pen/xxjoaRw

With v4.0.12  (Applying min-height on 2nd section)
https://codepen.io/alvarotrigo/pen/WNJqgRg

**Comment by alvarotrigo** [comment]
The same issue happened in V3 if the user defines the `height` and the same will happen now even if we change the CSS.
We'll fix the `min-height` issue but the `height` will one will stay.

So my question was whether this is an actual problem due to any WP config that adds that `min-height` instead of a `height` property.  (As the `height` one existed in V3 as well)

**Comment by meceware** [comment]
> We'll fix the min-height issue but the height will one will stay.

All right, thank you! I mean the height should not matter anyway for the section since it's an auto-height section.

> So my question was whether this is an actual problem due to any WP config that adds that min-height instead of a height property.

That's right! The new Elementor configuration adds the `min-height` directly to the section. It wasn't there before so the old versions work with both updates however with the latest Elementor update, `min-height` seems to conflict.

**Comment by alvarotrigo** [comment]
> That's right! The new Elementor configuration adds the min-height directly to the section. It wasn't there before so the old versions work with both updates however with the latest Elementor update, min-height seems to conflict.

Right, now I get it :)

**Comment by alvarotrigo** [comment]
Fixed in version 4.0.10! 🥳

**Comment by meceware** [comment]
Hi,

I think this issue still persists: Please see

https://github.com/alvarotrigo/fullPage.js/blob/master/dist/fullpage.css#L210

```
.fp-auto-height.fp-section,
.fp-auto-height .fp-slide{
    height: auto !important;
    min-height: auto !important; /* <<<< */
}
```

should be

```
.fp-auto-height.fp-section,
.fp-auto-height .fp-slide{
    height: auto !important;
}
```

Don't you think?

**Comment by alvarotrigo** [comment]
Yeap, you are right!
Fixed!
