### ISSUE TITLE
Avoid accidental scrolling when reading content in the bottom of the slide

### ISSUE THREAD

**Issue by elahmo** [alvarotrigo/fullPage.js#941]
I am having one interesting behavior where some of the slides have content which is positioned at or near the bottom of the pages. So, on smaller screens where the content can't be shown all at once, when the user scrolls down to see the content, he or she might *overscroll* (via mouse or touch pad) and instead of just scrolling to see the content trigger the new page slide in as well, so the user can't read the content and has to go back.

One solution might be too change the content structure and add some padding or empty space below the actual content, but that seems like crude solution. 

Is there a way to solve this so in the initial scroll, when the user is actually scrolling the page which has height larger than the screen/window height, doesn't trigger the scroll event?

Thanks

**Comment by alvarotrigo** [comment]
Already treated [here](https://github.com/alvarotrigo/fullPage.js/issues/294) and [here](https://github.com/alvarotrigo/fullPage.js/issues/286)

I will keep this one open and close #294 as this one is better presented.

**Comment by elahmo** [comment]
Sorry for opening the already discussed issue. I did try to find similar issues but was overwhelmed with questions and didn't try that exact wording while searching.

Do you think its possible to solve this in this way:

* detect is the height of the page larger than the current height of the window
* if so, temporarily disable the plugin
* after scrolling, check is the end of the page reached
* **if the end of the page is reached**, use a funciton like [this](http://documentcloud.github.io/underscore/#debounce), which would enable the plugin again
* when the scroll is activated, the plugin would activate

The function I linked, `_.debounce()` has an interesting behavior that is applicable in this case. It would be triggered **only** after some time has passed after the scroll event has stopped, lets say some arbitrary three digit number of milliseconds, `300`. 

So, if a user gets to the page that is larger in height than the window height, the plugin would be disabled. While the user scrolls, nothing would happen, **unless** the end of the page is reached. After the end/bottom of the page is reached, **and** the scroll event has been stopped for some period of time, that would re-enable the plugin and in the next scroll event, the expected behavior for the user would be to go to the next slide. In case of continuous scroll from the top to the bottom of the active page, the plugin wouldn't activate and used would have to "pause" for a moment.

There would be no additional dependencies as the function doesn't use anything specific to underscore.js (more [here](http://davidwalsh.name/function-debounce)).

**Comment by alvarotrigo** [comment]
The problem comes when dealing with Apple trackpads / trackpads in general and Apple Magic mouse.
There scroll behaviour keeps firing even after 1 second depending on the acceleration of the scrolling. 

I guess the way to go would be to force the user to reach the bottom, and then, after another scroll from the user, scroll the section. But the problem here is how we define the "2nd scrolling". As the scrolling event can be firing for 1 second after the user stops scrolling...

**Comment by d13** [comment]
I actually added a debounce function into my local version a few weeks ago and am using it only on the MouseWheelHandler with a 50ms wait. It seems to handle the problem well.

**Comment by Canubiz** [comment]
@elahmo @alvarotrigo – I added some additional checks to the scrolling() function in my local version of fullpage.js to solve this issue in a project I am working on right now. Basically I am requiring users of my website to first scroll down to the bottom of a scrollable section, then stop there and wait for 750ms before scrolling again to move on to next section. Up until now, this seems like the most natural and intuitive behavior of visitors who want to read content at the bottom of a section. If you're interested, here is my modified scrolling() function (see //EXTRA CHECK… comments for my additions):

```javascript
//EXTRA CHECK TO PREVENT EARLY SECTION SCROLLING
var lastScrollTime = 0;

function scrolling(type, scrollable){
    if (!isScrollAllowed[type]){
        return;
    }
    var check, scrollSection;

    if(type == 'down'){
        check = 'bottom';
        scrollSection = FP.moveSectionDown;
    }else{
        check = 'top';
        scrollSection = FP.moveSectionUp;
    }
	
	
    //EXTRA CHECK TO PREVENT EARLY SECTION SCROLLING
    var currentScrollTime = new Date().getTime();
    var lastScrollTimeDiff = currentScrollTime - lastScrollTime;
    lastScrollTime = currentScrollTime;

    if(scrollable.length > 0 ){
        //is the scrollbar at the start/end of the scroll?
        if(isScrolled(check, scrollable)){
            
            //EXTRA CHECK TO PREVENT EARLY SECTION SCROLLING
            if (lastScrollTimeDiff>750) {
                scrollSection();
			}
        }else{
            return true;
        }
    }else{
        // moved up/down
        scrollSection();
    }
}
```

What do you think? Does this also work for you? Is this a change that could make it into the next release of fullpage.js?

**Comment by alvarotrigo** [comment]
@Canubiz I think that might cause problems in devices with kinetic scrolling such as Apple track-pads. They might have difficulties scrolling down because of the scrolling inertia and they will have to stop scrolling for more than 750 milliseconds.

**Comment by Canubiz** [comment]
@alvarotrigo Thanks for your feedback. I developed this modification on a MacBook Air esp. testing its trackpad control and it seems to work exactly the way I'd expect to. I believe it's exactly the way scrolling on a fullpage website, including more content on a single section than it can fit, should behave: not scroll over that content at the bottom of a section, but stop there and require another, separate scroll attempt (detected but a short amount of time without any scroll events recognized) to move on to the next section.
The value of 750ms is for sure something open for debate and fine tuning. I also tried with much lower values like 250ms and it still works very well, maybe even better…? So maybe, with a lower value we can still reach the purpose to stop over-scrolling scrollable section content but still serve visitors well who want to quickly jump to the next section.
Note: this modification does not influence scrolling behavior of sections without scrollable content inside them. So in conclusion, if one does not have scrollable sections, this should change nothing in user experience. On the other hand, if one uses scrollable sections, user experience dramatically improves, at least from my point of view, as users cannot easily over scroll any content they wanted to go to and read.
I will do some more testing with the separate Apple Magic Trackpad and the Magic Mouse as well as trackpads on some other Mac models from friends and family and will come back with results, if you're interested. :)

**Comment by alvarotrigo** [comment]
Could you provide a link where I can test it? 
I still thinking that it will cause problems when swiping fast repeatedly, but I'll give it a try.

**Comment by Canubiz** [comment]
Sure, you can check it out here: http://polecious.at/studio/_betterscrolling/

**Comment by elahmo** [comment]
@Canubiz Thanks for your efforts. I tested this on my iPad, and the scrolling works but the kinetic effect is no longer there, meaning as soon as a lift my finger, the scrolling on the portions that should be scrolled stops. This is a bit counterintuitive, since most of the users usualy "flick" on tablets and expect the page to continue with that inertia, so that part is a bummer...

But that might have nothing to do with your code, since I think I noticed this as well when testing stuff before on my version as well...

**Comment by Canubiz** [comment]
@elahmo Thanks for checking out my modification! 

Indeed, I believe the lack of inertia is because the Slimscroll.js framework being used here doesn't support it at all. So, please correct me if wrong, but I think the lack of inertia when scrolling within a section should also be present in the original examples provided with the fullpage.js project.

There even is an issue thread here discussing if using iScroll instead of slimscroll framework to improve the way scrolling looks and feels: #623

**Comment by MuTLY** [comment]
Instead of using Slimscroll.js for the parts that exceed the height of the slide panel, why don't you just use, say, a <DIV> with 'overscroll: auto'?

I know the scrollbars won't be as nice as Slimscroll.js's, but I think that would solve the inertia problem on mobile, right? So maybe check if it's a mobile device and just go with 'overflow: auto', if not, use Slimscroll.js.

**Comment by alvarotrigo** [comment]
> Instead of using Slimscroll.js for the parts that exceed the height of the slide panel, why don't you just use, say, a <DIV> with 'overscroll: auto'?

You can, but it won't work at all in touch devices plus the scrolling bar looks a bit ugly :)

I would encourage you to try iScroll.js. fullPage.js is not adopting it at the moment because it doesn't provide compatibility with IE 9.

**Comment by Canubiz** [comment]
@MuTLY - I assume you mean "overflow" not "overscroll", right? According to CSS scrolling with momentum using this property should actually work, however at least on iOS. Not sure about other touch devices. This would be the code required according to https://css-tricks.com/snippets/css/momentum-scrolling-on-ios-overflow-elements/ (have not yet checked though):
```css
overflow-y: scroll; /* has to be scroll, not auto */
-webkit-overflow-scrolling: touch;
```

**Comment by MuTLY** [comment]
@Canubiz yes, my bad, I was talking about 'overflow: auto', in fact your example is exactly what I meant. I believe mobile devices do use the 'momentum' with the CSS mentioned, and I know for sure that Windows Phone 8 uses that (along with iOS and the -webkit- prefix).

Not sure about Android, but I think it goes the same way. So maybe a solution would be to check if there's 'movement' on the scrolling (swipe), say check for X milliseconds if the scrollTop changes. If it doesn't change then we reached the end of that DIV with overflow and now we call the method to advance to the next slide (up or down).

@alvarotrigo I did use iScroll on some projects and it behaves bad on some Windows Phones, so I had to change my mind about presenting cool scrollbars to the user OR presenting them a better scrolling experience. Turns out I had to switch off iScroll on this case and only use it on other devices. As for the scrolling itself, it worked without problems with just the 'overflow:auto' CSS for the Windows phones.

In my opinion, the user, on a mobile device, rarely, and I mean RARELY uses scrollbars to navigate up and down / left and right on web pages and/or apps. The scrollbars don't even show up on some devices, so why should I bother? :)

**Comment by alvarotrigo** [comment]
@MuTLY many people like to have the scroll bar in a side, not as an input element to scroll up or down, but as a way to tell the user they can keep scrolling down. More an issue of user experience in this case.

Using `overflow:scroll` won't show an scroll bar.

**Comment by reddo** [comment]
I've tried @Canubiz 's solution and it's not working with the current version :(

**Comment by alvarotrigo** [comment]
@reddo the issue still open, there's no proper solution for it.

**Comment by reddo** [comment]
@alvarotrigo have you considered using a different plugin instead of sclimscroll? Maybe [jQuery custom content scroller](http://manos.malihu.gr/jquery-custom-content-scroller/) or [TinyScrollbar](http://manos.malihu.gr/jquery-custom-content-scroller/)?

**Comment by alvarotrigo** [comment]
@reddo I have, but the solution doesn't seem perfect. Take a look [at this topic](https://github.com/alvarotrigo/fullPage.js/pull/1498). The changes were commited to the DEV branch. You can try to create a module for any other plugin, but right now it is using slimScroll and you have the [gist for iScroll.js here](https://gist.github.com/rmarscher/5f3a62b960f5f903a6af).

**Comment by reddo** [comment]
Gave it a try and it seems to work fine. I've also tried with ie9 and I didn't see a problem. I don't need support for ie8, so that shouldn't be an issue.

**Comment by alvarotrigo** [comment]
@reddo the scroll bar just doesn't look as nice as it's the default one for Windows machines.

**Comment by pinipints** [comment]
@reddo can you please share your code/approach on integrating iscroll in full page.js
Thanks in advance

**Comment by reddo** [comment]
@pinipints I've just followed @alvarotrigo's instructions 3 posts up. I did have to make some small edits to the linked gist code though. I'de be more than glad to share that code, if you want.

Basically I downloaded the fullpage.js from the dev branch linked, included the _modified_ code from the gist and it just worked.

**Comment by alvarotrigo** [comment]
@pinipints @reddo the branch is no longer necessary. It was merged yesterday with the main project.

Here you have [a demo online using iScroll.js](http://alvarotrigo.com/fullPage/prueba/examples/iscroll.html#firstPage). You will only need to place [this code](https://gist.github.com/alvarotrigo/620c53c644f252b43f68) at the bottom of fullpage.js code, just before the closing brackets. As it is [here](http://alvarotrigo.com/fullPage/prueba/jquery.fullPage.js).

**Comment by reddo** [comment]
@alvarotrigo I still had to change bits of the gist code, specifically lines 36 and 37 have some variables defined with `let`, I had to change those to `var` otherwise my uglify task threw an error.

**Comment by alvarotrigo** [comment]
@reddo don't know about uglify, but the gist I just posted works as you can see on the demo page I linked. In any case, I would also change that to `var` as you said.

**Comment by pinipints** [comment]
@reddo i get errors on safari and firefox due to the variables defined with ```let``` while on google chrome it loads fine.
@alvarotrigo thanks for having that demo page with iscroll. changing the ```let``` with ```var``` may help making it compatible with all browsers
i will give it a try today, thanks once again

**Comment by reddo** [comment]
@pinipints I changed `let` to `var` on lines 36 and 37 of the *gist* and it worked just fine. Good luck

**Comment by pinipints** [comment]
@reddo yes thanks.. same, i changed ```let``` to ```var``` and it worked for me on all browsers.
thanks once again for all the help :)

**Comment by adrien-be** [comment]
Hi all, what about triggering the scroll to the next section only if a good part (let's they at least 1/3rd) of the viewport is on the next section?

This solution should be easy enough to implement. And one could provide a new option parameter to let the dev choose what value works better.

**Comment by alvarotrigo** [comment]
> This solution should be easy enough to implement.

You can create a pull request for it.

**Comment by adrien-be** [comment]
Yeah, I will try to implement it and create PR if I am successful

**Comment by choujar** [comment]
@adrien-be did you have any luck with it?

**Comment by adrien-be** [comment]
I didn't get the chance to implement this actually as I ran in other
unrelated ux issues.
I hope you manage to do this.

**Comment by rbosneag** [comment]
After the switch to iScroll it seems that on iOS 9.3.2/iPhone 6S this is not an issue anymore! I still have issues though on OSX (Chrome, Safari and Firefox)

**Comment by reddo** [comment]
I'm trying a different approach right now and it seems to be working. Here's my scrolling function at the moment:``

**Comment by alvarotrigo** [comment]
> This method stops the scrolling for 250ms once you hit the bottom of the div for the 1st time, resets the variable and you can scroll on the next time.

Looks like you'll have problems with kinetic scrolling (Apple trackpads, magic mouse...)

**Comment by reddo** [comment]
It's working fine on my macbook for the time, I'll keep testing to check if it's viable long-time. I'll tweak the timeout a bit to see what's best.

**Comment by alvarotrigo** [comment]
@reddo try scrolling fast, then waiting 250 milliseconds (just a bit) and then try scrolling fast again. 
The scrolling inertia should should keep firing scrolling events for more than 250 milliseconds and, if the inertial scrolling is accelerating (this is an improvement since the topic was opened), then you should be stuck in the section until the inertia stops.

**Comment by alvarotrigo** [comment]
@reddo by the way, shouldn't you be clearing your timeout? Otherwise what you are getting is just a delayed scrolling, but that will take place even after the smallest scrolling, like it happens now.

**Comment by reddo** [comment]
I've updated the gist to account for scrolling direction ad increased the timeout a bit and added some comments: [(see gist)](https://gist.github.com/reddo/d7ab532e03ffb41b3fa9870aab0a1d09). 

@alvarotrigo It really is working good, even using my trackpad (MacBook Pro Retina, 13-inch, Early 2015; with latest OsX and Chrome). 

I don't clear the timeout because I want the page to scroll to the next section if the user keeps scrolling. I'm not saying this is the best solution, but I just wanted to share in case I can help someone else.

**Comment by db-24** [comment]
@reddo really interesting conversation, I too am requiring a solution to this scrolling issue. I'd like to test the gist you've amended. Could you advise on usage as i'm not proficient in js - am I supposed to copy the gist and replace the corresponding section in the jquery.fullPage.js file??

... I have tried this but it kills the scrolling completely except when using the nav buttons... 

@alvarotrigo are you in support of the gist or are you still seeing potential issues?

Thanks,

**Comment by alvarotrigo** [comment]
@db-24  I haven't tested it myself. So I can not say much. But I do not see any `clearTimeout`, which means the timeout will always get fired no matter what the action of the user is. As it will always enter in the timeout the 1st time it reaches the top or the bottom.

My guess is, kinetic scrolling will keep firing mousewheel events that will kept being caught by the `scrolling` function (unless they are of less intensity the the previous ones average) and therefore this gist will only cause a 500 milliseconds delay, but will keep scrolling up or down when reaching the top or bottom with a single swipe in a Mac trackpad (or similar) 

To test it. I suggest a **fast** but single swipe in the trackpad / magic mouse when you are about to reach the end of the scrollable section.

**Comment by reddo** [comment]
@db-24: I'm using it successfully in a project without any issues. Let me see if it's the latest version, but I haven't had any problems with it so far whenever I updated the fullpage.js (I'm currently using the dev version). You just have to replace the function in the fullpage.js with the same name (currently from here: https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js#L1068 to line 1086)

@alvarotrigo: That is how I intended it. It should keep scrolling after the 500ms; I added that timeout just so I stop accidental scrolling, I still want to be able to scroll to the whole page if I want to, I don't want to have to stop after each section and start scrolling again, but I already explained this. Maybe someone needs it different, but right now it suits my needs perfectly.

**Comment by alvarotrigo** [comment]
> That is how I intended it. It should keep scrolling after the 500ms; I added that timeout just so I stop accidental scrolling

That means, you are not actually stopping accidental scrollings. You are just delaying them 500 ms no matter if it was by accident or not.

**Comment by reddo** [comment]
I'm not trying to stop scrolling in any way, I'm just stopping the user to accidentally switch sections

As of now, it is really hard to stop on the bottom of a section and not scroll over, that's what this hack fixes. I don't know if I can explain any clearer.

**Comment by reddo** [comment]
@db-24: maybe your issue is related to #2353 - it's fixed on dev.
I'm using dev version and it's working fine.

**Comment by db-24** [comment]
Thank you both for getting back to me. fullPage.js is excellent, my clients only gripe was the scrolling at the end of scrollable slides.

@reddo Thank you. It's exactly what I hoped it would be! Allows just enough to be able to hit the top or bottom of the slide (admittedly on slower scrolling) before pushing forward and continuing (with magic mouse). Excellent.

**Comment by bogdan-r** [comment]
@lanbomo it works great with MacBook trackpad. Thanks. I grab you solution.

**Comment by lanbomo** [comment]
@bogdan-r I'm glad to sound that. I will consider to put a Rull Request, hope it can help others more. Thanks for your test.

**Comment by alvarotrigo** [comment]
@lanbomo thanks for it! Seems it works as expected in some cases! 
I forgot to comment on this back on December, but as far as I could test on the day, it was only working properly on the 1st section? Or if you didn't scroll consecutively down section after section? I'll check it again whenever I have a Mac and provide you some feedback.

**Comment by lanbomo** [comment]
@alvarotrigo Thanks for your works. When scroll bar reached the end and scroll consecutively it will work. I don't know how about Mac's trackpad, but I think the option `delay` could help developer to adjust to an expected effect.

Finally, thanks for your works again.

**Comment by Pixelous** [comment]
Hi, @alvarotrigo will you merge @lanbomo solution? Did you test it?

**Comment by alvarotrigo** [comment]
@Pixelous I didn't test it yet.

**Comment by LukeTongue** [comment]
This works really well. Would be great if it can be merged into the master as i would like to use this as well as the parallax extension.

**Comment by jk171505** [comment]
@alvarotrigo any chances to merge it into the master?

**Comment by alvarotrigo** [comment]
> @alvarotrigo any chances to merge it into the master?

Maybe.

**Comment by eliteproxy7** [comment]
how can i use this with fullpage.extensions.min.js ? i purchased 3/4 extensions and the fullpage.extensions.min.js file is obfuscated and i can't figure out this feature.. otherwise the overflow function becomes useless with the jump.. we did some usability testing and every single user complained that it jumped and they missed the content

**Comment by alvarotrigo** [comment]
> how can i use this with fullpage.extensions.min.js ? i purchased 3/4 extensions and the fullpage.extensions.min.js file is obfuscated and i can't figure out this feature

@eliteproxy7 you are mixing things here. This issue has nothing to do with the extensions. 
You have the same issue with the [jquery.fullpage.js](https://github.com/alvarotrigo/fullPage.js/blob/master/jquery.fullPage.js) file that you can examine as long as you want :)

**Comment by jayelm** [comment]
I minified @lanbomo's modifications and generated production RawGit links for the minified versions in [this repo](https://github.com/jayelm/fullPage.js/tree/dev). Until this gets merged (which I hope it does), the quickest way to implement his fix is to swap out whatever version of `jquery.fullpage.min.js` you're loading with the one available here (the other files can stay the same):

https://cdn.rawgit.com/jayelm/fullPage.js/dev/dist/jquery.fullpage.min.js

Then add the following option to your `fullpage` call to use the default settings, which work well:

    scrollOverflowEndPrevent: { delay: 500, reversal: false }

(@lanbomo, feel free to do the same for your repository, and I can update the links here.)

**Comment by lanbomo** [comment]
@jayelm Thanks for your work.

**Comment by alieslamifard** [comment]
Hi,
this is my solution,
1. first of all, put a div with class: section-end in every section with this style:
`.section{position:relative}`
`.section-end{position:absolute;bottom:0;left:0;right:0;width:100%;opacity:0;height:1px}`

2. then, use this callback:
`onLeave: function(index, nextIndex, direction){
            var leavingSection = $(this);

            if (direction =='down') {
                if(index == 2 || index == 3 || index == 4){
                    var w = $(window).height(),
                        end = leavingSection.find('.section-end').offset().top;
                        console.log(w, ' ', end);
                    if ( end > w  ) {
                        return false;
                    }

                }
            }
        }`

**Comment by monfortm** [comment]
@jayelm @lanbomo thanks guys, I could test the solution quite fast thank to the CDN, it's a great work from @jayelm and work as expected.

For me a value of 100ms is just enough to prevent brute 💪 users to accidentally go down 1 section when they were just checking for more content. And it does not prevent normal behavior on section without scrollOverflow.

@alvarotrigo Thanks for your work, great lib. I would really like to see @jayelm 's solution merged into the master branch 😄 

I personally tested it on mac:  firefox 58.0.2, chrome 64.0.3282.140 and safari 11.0.3 (13604.5.6) 🤖 

cheers,
m

**Comment by jayelm** [comment]
@monfortm not my solution, all @lanbomo's, I just packaged it up!

**Comment by monfortm** [comment]
@jayelm I understood that, but with your package and CDN I could test the solution in 3sec 👍 , that is why I was thanking both of you, cheers.

**Comment by alvarotrigo** [comment]
I would need to review this with more calm, it is a big amount of the code the one added for such a small feature.

Original code:
```javascript
        isScrolled: function(type, scrollable) {
            var scroller = scrollable.data('iscrollInstance');

            //no scroller?
            if (!scroller) {
                return true;
            }

            if (type === 'top') {
                return scroller.y >= 0 && !scrollable.scrollTop();
            } else if (type === 'bottom') {
                return (0 - scroller.y) + scrollable.scrollTop() + 1 + scrollable.innerHeight() >= scrollable[0].scrollHeight;
            }
```

Suggested code:

```javascript
     isScrolled: function(type, scrollable) {
            var scroller = scrollable.data('iscrollInstance');

            //no scroller?
            if (!scroller) {
                return true;
            }
            
            var endPreventLastY = scrollable.data('iscrollInstanceEndPreventLastY');
            var endPreventDirection = scrollable.data('iscrollInstanceEndPreventDiriction');
            var endPreventScrollTop = scrollable.data('iscrollInstanceEndPreventScrollTop');
            var endPreventTopTime = scrollable.data('iscrollInstanceEndPreventTopTime');
            var endPreventBottomTime = scrollable.data('iscrollInstanceEndPreventBottomTime');
            
            // reversal action work with the scroll-end-prevent function?
            if(!iscrollEndPreventOptions.reversal && 
                ((endPreventLastY >= 0 && !endPreventScrollTop && type === 'bottom')
                || ((0 - endPreventLastY) + endPreventScrollTop + 1 + scrollable.innerHeight() >= scrollable[0].scrollHeight && type === 'top'))
            ){
                if(endPreventDirection !== scroller.directionY){
                    scrollable.data('iscrollInstanceEndPreventLastY', scroller.y);
                    scrollable.data('iscrollInstanceEndPreventDiriction', scroller.directionY);
                    scrollable.data('iscrollInstanceEndPreventScrollTop', scrollable.scrollTop());
                }
            }
            
            if (type === 'top') {
                scrollable.data('iscrollInstanceEndPreventBottomTime', 0);
                if(scroller.y >= 0 && !scrollable.scrollTop()){
                    if(endPreventTopTime === 0){
                        var time = new Date().getTime();
                        scrollable.data('iscrollInstanceEndPreventTopTime', time);
                        endPreventTopTime = time;
                    }
                    if(endPreventLastY >= 0 || new Date().getTime() - endPreventTopTime >= iscrollEndPreventOptions.delay){
                        scrollable.data('iscrollInstanceEndPreventLastY', scroller.y);
                        return true;
                    }
                }
                return false;
            } else if (type === 'bottom') {
                scrollable.data('iscrollInstanceEndPreventTopTime', 0);
                if((0 - scroller.y) + scrollable.scrollTop() + 1 + scrollable.innerHeight() >= scrollable[0].scrollHeight){
                    if(endPreventBottomTime === 0){
                        var time = new Date().getTime();
                        scrollable.data('iscrollInstanceEndPreventBottomTime', time);
                        endPreventBottomTime = time;
                    }
                    if((0 - endPreventLastY) + scrollable.scrollTop() + 1 + scrollable.innerHeight() >= scrollable[0].scrollHeight || new Date().getTime() - endPreventBottomTime >= iscrollEndPreventOptions.delay){
                        scrollable.data('iscrollInstanceEndPreventLastY', scroller.y);
                        return true;
                    }
                }
                return false;
            }
        },
```

**Comment by alvarotrigo** [comment]
@monfortm  just notice you will be using version 2.9.2 instead of the current 2.9.6 (tends of bugs solved since then).

I would encourage you to modify the scrolloverflow.js `isScrolled ` function instead of using the forked fullpage.js file, which is far from being up to date and contains bugs.

**Comment by monfortm** [comment]
@alvarotrigo Thanks for the input, no worries, I am actually not using this forked version from @lanbomo, I just used it for testing the feature. 

The website I have is in prod so I am using the official fullpage.js. I have a fullPage.js @ fc34fb06 as git submodule in my repo (should be 2.9.5, no noticeable bugs for me).

my post was more to convey the fact that I tried the feature and I like it 😸

**Comment by alvarotrigo** [comment]
@monfortm you can always check the list of solved bugs in the [releases description](https://github.com/alvarotrigo/fullPage.js/releases). You'll notice 16 bugs were fixed since 2.9.5.

**Comment by IharSivakLeverx** [comment]
Hello @alvarotrigo you forgot about iscrollEndPreventOptions in function

**Comment by alvarotrigo** [comment]
@IharSivakLeverx thanks for pointing it out!

**Comment by drew-haas** [comment]
@jayelm this looks like a great solution but I can't get it to work on my project.  I get the error `Uncaught ReferenceError: IScroll is not defined`.  It looks like this was fixed in a more recent version than the one being used (2.9.2) (https://github.com/alvarotrigo/fullPage.js/issues/2250).  

I was wondering if there is a way to update your code with the latest version of fullpage (2.9.6).

Thanks again!

**Comment by minlare** [comment]
@alvarotrigo Is there any decision on whether this change will be merged into main branch?

**Comment by alvarotrigo** [comment]
@minlare not yet. I'm working on other things at the moment and didn't have time to check this with calm.

**Comment by Paperweb** [comment]
I ran across the same issue, as probably did many people using scrollOverflow, if not all of them since it is such an important UX matter.

So I decided to try @Canubiz 's solution after attempting in vain to modify scrollOverflow.js and jquery.fullPage.js with @lanbomo's + @alvarotrigo's [excerpt](https://github.com/alvarotrigo/fullPage.js/issues/941#issuecomment-364478343) and [suggestion](https://github.com/alvarotrigo/fullPage.js/issues/941#issuecomment-364478723) in a way that would'nt be cumbersome to update at every new fullPage release.

For those interested, I adapted Canubiz's solution to jquery.fullPage.j 2.9.7 :

**_From line 1055_**
 		
      // Added lines to prevent early section scrolling : variables
      var lastScrollTime = 0;                                           /* <-- added */
      var scrollTimeDelay = 250;                                        /* <-- added */

      function scrolling(type){
         if (!isScrollAllowed.m[type]){
               return;
         }

      var scrollSection = (type === 'down') ? moveSectionDown : moveSectionUp;

      if(options.scrollOverflow){
         var scrollable = options.scrollOverflowHandler.scrollable($(SECTION_ACTIVE_SEL));
         var check = (type === 'down') ? 'bottom' : 'top';

         // Added lines to prevent early section scrolling : get the scroll interval
         var currentScrollTime = new Date().getTime();                  /* <-- added */
         var lastScrollTimeDiff = currentScrollTime - lastScrollTime;   /* <-- added */
         lastScrollTime = currentScrollTime;                            /* <-- added */

         if(scrollable.length > 0 ){
            //is the scrollbar at the start/end of the scroll?
            if(options.scrollOverflowHandler.isScrolled(check, scrollable)){
               if (lastScrollTimeDiff>scrollTimeDelay) {                /* <-- added */
                  scrollSection();
               }                                                        /* <-- added */
            }else{
               return true;
            }
         }else{
            // moved up/down
            if (lastScrollTimeDiff>scrollTimeDelay) {                   /* <-- added */
               scrollSection();
            }                                                           /* <-- added */
         }
         }else{
            // moved up/down
            // Add IF here too when delay is needed and scrollOverflow : false
            scrollSection(); 
         }
      }

It's working pretty well for me. Maybe @reddo's [commented that it didn't work](https://github.com/alvarotrigo/fullPage.js/issues/941#issuecomment-155422706) because he replaced the whole snippet with Canubiz's?

As Alvarò says, I guess further testing is still necessary to make sure it doesn't alter the experience on momentum driven devices.

But for now, it is a workaround that is easy to update and works as intended for my needs. Thanks @Canubiz and everyone else involved here! I'll be following that issue.

**Comment by jscti** [comment]
That's perfect @Paperweb Thanks.

Hope a official fix get released some day ;)

**Comment by goowikns** [comment]
This thread is really confusing. 

Paperweb talks about a solution being adapted to jquery.fullPage.j 2.9.7... 
alvarotrigo closes the thread, which means in my opinion that the fix would be pushed, but when I check the file (https://cdnjs.cloudflare.com/ajax/libs/fullPage.js/2.9.7/jquery.fullpage.js), I can't seem to find any of it.

And this has been going on since 2015?

Could there, please, be a clear answer on when this will be released on a 2.9.x

**Comment by alvarotrigo** [comment]
> Could there, please, be a clear answer on when this will be released on a 2.9.x

Nothing else will be released for version 2.X.

> alvarotrigo closes the thread, 

Nop, the issue stills open :)

**Comment by SavageSage** [comment]
no luck on this since 2015?

**Comment by alvarotrigo** [comment]
> no luck on this since 2015?

Apparently nobody was able to come with a solution as you can read in the comments 🤔 
So nope. No solution for it yet.

**Comment by JulianBroudy** [comment]
Just throwing ideas here, would it be possible to disable scrolling entirely once a section with the scrollOverflow is activated and maybe create some kind of listener to the added scroll so once it hits the end, then enable the scrolling again?
If it would result in the same behavior then maybe set a timeout before enabling it?

**Comment by kaletvintsev** [comment]
Did You try using something like this:
```
function blocking() {
            window.clearTimeout(isScrolling);
            isScrolling = setTimeout(function () {
                can_scroll_top = true
            }, 66);
        }
```
I propose to evaluate this function on scroll or wheel event and disable scrolling if  can_scroll_top === true

**Comment by alvarotrigo** [comment]
@JulianBroudy most people complaining about this are using kinetic scrolling devices, rather on Apple devices or laptops trackpads. 

Fixing it for normal devices can also become annoying for visitors. If they want to keep on scrolling down and we prevent them to do so based on a timeout and they keep on trying to scroll, it won't slide down. They'll have to stop scrolling for some time before scrolling down.

**Comment by rstanuwijaya** [comment]
Hi, I'm currently working on merging the @lanbomo solution with v3.x.

For people who would like to manually implement the @lanbomo solution, you can just simply use my modified version of scrolloverflow.js [here](https://github.com/rstanuwijaya/fullPage.js/blob/scrolloverflow-endprevent/vendors/scrolloverflow.js)

@alvarotrigo I think it is way better to apply a delay, as in the current version  I cannot see the top and bottom of the page without accidentally scrolling it.

**Comment by alvarotrigo** [comment]
@rstanuwijaya I'm working on fullPage.js version 4, which will NOT include iScroll.js. 

> @alvarotrigo I think it is way better to apply a delay, as in the current version I cannot see the top and bottom of the page without accidentally scrolling it.

Using a mouse wheel? A trackpad? Or a touch device?

**Comment by rstanuwijaya** [comment]
I'm having this problem especially when I'm using my mouse wheel. It always jumps to the next section without being able to reach the most bottom part of the page.

**Comment by alvarotrigo** [comment]
Good to know.

**Comment by oussamatb** [comment]
So Guys apparently when we add speed to the scroll it helps avoiding overscroling the page   
scrollingSpeed: 1000,
I hope this helps !

**Comment by alvarotrigo** [comment]
> So Guys apparently when we add speed to the scroll it helps avoiding overscroling the page

Yeap.

**Comment by alvarotrigo** [comment]
Version 4 has gotten rid of the vendor file scrolloverflow.min.js.

And this should now be fixed! 🥳

**Comment by alvarotrigo** [comment]
It feels good closing an issue 7 years old! :)
