### ISSUE TITLE
When i resize, I am getting errors..

### ISSUE THREAD

**Issue by ashishg656** [alvarotrigo/fullPage.js#970]
i get errors when i resize the browser..
I am using firefox 35.0

If i use non-minified version,
<script type="text/javascript" src="onepagescroll/js/jquery.fullPage.js"></script>

I get the following error--

TypeError: destinyPos is undefined

![1](https://cloud.githubusercontent.com/assets/10696242/5891884/7066d006-a4d1-11e4-8a66-05895e4bb46a.jpg)

If i use the minified version,
<script type="text/javascript" src="onepagescroll/js/jquery.fullPage.min.js"></script>
i get this error on resize---

TypeError: e is undefined

![2](https://cloud.githubusercontent.com/assets/10696242/5891892/e426203c-a4d1-11e4-9ca2-76ac7114eb95.jpg)

My Fullpage initialisation code----------------------

$(document).ready(function() {
    
    $('#fullpage').fullpage({
				scrollBar: true,	
	});
});

Help me
I am using latest version
2.5.5 of fullpage js

**Comment by ashishg656** [comment]
I am using latest version
2.5.5 of fullpage js

**Comment by alvarotrigo** [comment]
You should provide your HTML markup as well. The problem can be there.

**Comment by ashishg656** [comment]
I just trie if there is error in demo file.
And yes, I am getting same erro in demo file --
This is scrollBar.html (unedited)
Firefox 35.0
Latest FullPage plugin downloaded today only..

![1](https://cloud.githubusercontent.com/assets/10696242/5893091/806c44c8-a4fd-11e4-95a1-c6ec9f6ccc42.jpg)

**Comment by alvarotrigo** [comment]
I will take a look at it tomorrow.

**Comment by ashishg656** [comment]
Sure plz help me

**Comment by alvarotrigo** [comment]
Solved in 2.5.6.

**Comment by ashishg656** [comment]
Thankyou so much :)

**Comment by ashishg656** [comment]
Sir in my markup, i am still getting the same error..Can you help me what to do to get error correct in my markup plz.

**Comment by alvarotrigo** [comment]
> Sir in my markup, i am still getting the same error.

Then you should publish your makup or provide a link so I can take a look at it. But its probably because you are doing something wrong. The error in the demo page has disappeared.
